# syntax=docker/dockerfile:1

FROM node:24-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd

WORKDIR /app
COPY server.mjs traffic.mjs deactivation-traffic.mjs /app/

EXPOSE 3000
CMD ["node", "/app/server.mjs"]
