<?php

namespace App\Actions\Proxy;

final class DurableRemoteArtifact
{
    /** @return list<string> */
    public static function shellFunctions(): array
    {
        return [
            'durable_remote_owner_uid() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%u" "$1" >/dev/null 2>&1; then stat -c "%u" "$1"; else stat -f "%u" "$1"; fi',
            '}',
            'durable_remote_link_count() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%h" "$1" >/dev/null 2>&1; then stat -c "%h" "$1"; else stat -f "%l" "$1"; fi',
            '}',
            'durable_remote_permissions() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'durable_remote_assert_owned_directory() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  [ -d "$1" ] && [ ! -L "$1" ] || return 1',
            '  [ "$(durable_remote_owner_uid "$1")" = "$(id -u)" ] || return 1',
            '  durable_remote_directory_permissions=$(durable_remote_permissions "$1") || return 1',
            '  case "$durable_remote_directory_permissions" in ???|????) ;; *) return 1 ;; esac',
            '  case "$durable_remote_directory_permissions" in *[!0-7]*) return 1 ;; esac',
            '  durable_remote_other_permissions=${durable_remote_directory_permissions#"${durable_remote_directory_permissions%?}"}',
            '  durable_remote_owner_group_permissions=${durable_remote_directory_permissions%?}',
            '  durable_remote_group_permissions=${durable_remote_owner_group_permissions#"${durable_remote_owner_group_permissions%?}"}',
            '  case "${durable_remote_group_permissions}${durable_remote_other_permissions}" in *[2367]*) return 1 ;; esac',
            '}',
            'durable_remote_assert_owned_regular() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  [ -f "$1" ] && [ ! -L "$1" ] || return 1',
            '  [ "$(durable_remote_owner_uid "$1")" = "$(id -u)" ] || return 1',
            '  [ "$(durable_remote_link_count "$1")" = 1 ] || return 1',
            '}',
            'durable_remote_cleanup_owned_regular_prefix() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$1" || return 1',
            '  case "$2" in .?* ) ;; *) return 64 ;; esac',
            '  case "$2" in *[!a-z0-9.-]* ) return 64 ;; esac',
            '  for durable_remote_candidate in "$1"/"$2"*; do',
            '    if [ ! -e "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if [ -d "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    durable_remote_assert_owned_regular "$durable_remote_candidate" || return 1',
            '  done',
            '  durable_remote_removed=false',
            '  for durable_remote_candidate in "$1"/"$2"*; do',
            '    if [ ! -e "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if [ -d "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if ! durable_remote_assert_owned_regular "$durable_remote_candidate"; then',
            '      if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '      return 1',
            '    fi',
            '    if ! rm -f -- "$durable_remote_candidate"; then',
            '      if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '      return 1',
            '    fi',
            '    durable_remote_removed=true',
            '  done',
            '  if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '}',
            'durable_remote_replace() {',
            '  [ "$#" -eq 3 ] || return 64',
            '  durable_remote_assert_owned_directory "$3" || return 1',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || return 1',
            '    if [ -e "$2" ] || [ -L "$2" ]; then durable_remote_assert_owned_regular "$2" || return 1; fi',
            '    sync "$1" || return 1',
            '    if [ "${COOLIFY_DURABLE_REMOTE_ARTIFACT_CRASH_AFTER_CANDIDATE_FSYNC:-}" = 1 ]; then exit 75; fi',
            '    mv -f -- "$1" "$2" || return 1',
            '  else',
            '    durable_remote_assert_owned_regular "$2" || return 1',
            '    sync "$2" || return 1',
            '  fi',
            '  durable_remote_assert_owned_regular "$2" || return 1',
            '  sync "$3" || return 1',
            '}',
            'durable_remote_remove() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$2" || return 1',
            '  if [ -e "$1" ] || [ -L "$1" ]; then durable_remote_assert_owned_regular "$1" || return 1; fi',
            '  rm -f -- "$1" || return 1',
            '  if [ "${COOLIFY_DURABLE_REMOTE_ARTIFACT_CRASH_AFTER_UNLINK:-}" = 1 ]; then exit 75; fi',
            '  sync "$2" || return 1',
            '}',
            'durable_remote_reaffirm() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$2" || return 1',
            '  durable_remote_assert_owned_regular "$1" || return 1',
            '  sync "$1" || return 1',
            '  sync "$2" || return 1',
            '}',
        ];
    }
}
