<?php

namespace App\Actions\Proxy;

final class DurableRemoteArtifact
{
    /** @return list<string> */
    public static function shellFunctions(): array
    {
        return [
            'durable_remote_owner_uid() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%u" "$1" >/dev/null 2>&1; then stat -c "%u" "$1"; else stat -f "%u" "$1"; fi',
            '}',
            'durable_remote_link_count() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%h" "$1" >/dev/null 2>&1; then stat -c "%h" "$1"; else stat -f "%l" "$1"; fi',
            '}',
            'durable_remote_permissions() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'durable_remote_refuse() {',
            '  printf \'durable-remote: %s refused: %s\n\' "$1" "$2" >&2',
            '  return 1',
            '}',
            'durable_remote_assert_owned_directory() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  [ -d "$1" ] && [ ! -L "$1" ] || durable_remote_refuse "$1" "not a real directory" || return 1',
            '  [ "$(durable_remote_owner_uid "$1")" = "$(id -u)" ] || durable_remote_refuse "$1" "owner uid $(durable_remote_owner_uid "$1") is not the executing uid $(id -u)" || return 1',
            '  durable_remote_directory_permissions=$(durable_remote_permissions "$1") || durable_remote_refuse "$1" "permissions unreadable" || return 1',
            '  case "$durable_remote_directory_permissions" in ???|????) ;; *) durable_remote_refuse "$1" "permissions $durable_remote_directory_permissions malformed"; return 1 ;; esac',
            '  case "$durable_remote_directory_permissions" in *[!0-7]*) durable_remote_refuse "$1" "permissions $durable_remote_directory_permissions malformed"; return 1 ;; esac',
            '  durable_remote_other_permissions=${durable_remote_directory_permissions#"${durable_remote_directory_permissions%?}"}',
            '  durable_remote_owner_group_permissions=${durable_remote_directory_permissions%?}',
            '  durable_remote_group_permissions=${durable_remote_owner_group_permissions#"${durable_remote_owner_group_permissions%?}"}',
            '  case "${durable_remote_group_permissions}${durable_remote_other_permissions}" in *[2367]*) durable_remote_refuse "$1" "permissions $durable_remote_directory_permissions are group- or other-writable"; return 1 ;; esac',
            '}',
            'durable_remote_assert_owned_regular() {',
            '  [ "$#" -eq 1 ] || return 64',
            '  [ -f "$1" ] && [ ! -L "$1" ] || durable_remote_refuse "$1" "not a real regular file" || return 1',
            '  [ "$(durable_remote_owner_uid "$1")" = "$(id -u)" ] || durable_remote_refuse "$1" "owner uid $(durable_remote_owner_uid "$1") is not the executing uid $(id -u)" || return 1',
            '  [ "$(durable_remote_link_count "$1")" = 1 ] || durable_remote_refuse "$1" "hard link count is not 1" || return 1',
            '}',
            'durable_remote_cleanup_owned_regular_prefix() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$1" || return 1',
            '  case "$2" in .?* ) ;; *) return 64 ;; esac',
            // Enumerated class instead of a-z/0-9 ranges: POSIX pattern ranges follow the
            // host locale's collation, which can admit uppercase on remote hosts.
            '  case "$2" in *[!abcdefghijklmnopqrstuvwxyz0123456789.-]* ) return 64 ;; esac',
            '  for durable_remote_candidate in "$1"/"$2"*; do',
            '    if [ ! -e "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if [ -d "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    durable_remote_assert_owned_regular "$durable_remote_candidate" || return 1',
            '  done',
            '  durable_remote_removed=false',
            '  for durable_remote_candidate in "$1"/"$2"*; do',
            '    if [ ! -e "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if [ -d "$durable_remote_candidate" ] && [ ! -L "$durable_remote_candidate" ]; then continue; fi',
            '    if ! durable_remote_assert_owned_regular "$durable_remote_candidate"; then',
            '      if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '      return 1',
            '    fi',
            '    if ! rm -f -- "$durable_remote_candidate"; then',
            '      if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '      return 1',
            '    fi',
            '    durable_remote_removed=true',
            '  done',
            '  if [ "$durable_remote_removed" = true ]; then sync "$1" || return 1; fi',
            '}',
            'durable_remote_replace() {',
            '  [ "$#" -eq 3 ] || return 64',
            '  durable_remote_assert_owned_directory "$3" || return 1',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || return 1',
            '    if [ -e "$2" ] || [ -L "$2" ]; then durable_remote_assert_owned_regular "$2" || return 1; fi',
            '    sync "$1" || return 1',
            '    if [ "${COOLIFY_DURABLE_REMOTE_ARTIFACT_CRASH_AFTER_CANDIDATE_FSYNC:-}" = 1 ]; then exit 75; fi',
            '    mv -f -- "$1" "$2" || return 1',
            '  else',
            '    durable_remote_assert_owned_regular "$2" || return 1',
            '    sync "$2" || return 1',
            '  fi',
            '  durable_remote_assert_owned_regular "$2" || return 1',
            '  sync "$3" || return 1',
            '}',
            'durable_remote_remove() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$2" || return 1',
            '  if [ -e "$1" ] || [ -L "$1" ]; then durable_remote_assert_owned_regular "$1" || return 1; fi',
            '  rm -f -- "$1" || return 1',
            '  if [ "${COOLIFY_DURABLE_REMOTE_ARTIFACT_CRASH_AFTER_UNLINK:-}" = 1 ]; then exit 75; fi',
            '  sync "$2" || return 1',
            '}',
            'durable_remote_reaffirm() {',
            '  [ "$#" -eq 2 ] || return 64',
            '  durable_remote_assert_owned_directory "$2" || return 1',
            '  durable_remote_assert_owned_regular "$1" || return 1',
            '  sync "$1" || return 1',
            '  sync "$2" || return 1',
            '}',
        ];
    }
}
