<?php

namespace App\Actions\Proxy\ControlPlane;

use App\Actions\Proxy\DurableRemoteArtifact;
use InvalidArgumentException;
use Lorisleiva\Actions\Concerns\AsAction;

final class ManagedTraefikDocumentWriter
{
    use AsAction;

    public const APPLIED_OUTPUT = 'coolify-managed-traefik-document:applied';

    public const ROLLED_BACK_OUTPUT = 'coolify-managed-traefik-document:rolled-back';

    public const WRITER_AUTHORITY_PROMOTED_OUTPUT = 'coolify-managed-traefik-writer-authority:promoted';

    private const ARTIFACT_MAGIC = 'coolify-managed-traefik-document-rollback-v1';

    private const JOURNAL_MAGIC = 'coolify-managed-traefik-document-journal-v1';

    public function writeCommandFor(ManagedTraefikDocumentMutation $mutation): string
    {
        return $this->commandFor($mutation, false);
    }

    public function rollbackCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        bool $allowMissingArtifactNoop = false,
    ): string {
        return $this->commandFor(
            mutation: $mutation,
            rollback: true,
            allowMissingArtifactNoop: $allowMissingArtifactNoop,
        );
    }

    public function writeCommandForRequiringAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $activeAuthority,
        bool $allowBootstrap,
    ): string {
        $this->assertDocumentWriteAuthority($mutation, $activeAuthority, $allowBootstrap);

        return $this->commandFor(
            mutation: $mutation,
            rollback: false,
            requiredAuthority: $activeAuthority,
            allowAuthorityBootstrap: $allowBootstrap,
        );
    }

    public function promoteWriterAuthorityCommandFor(
        string $stateDirectory,
        string $filename,
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): string {
        $this->assertWriterAuthorityContext($stateDirectory, $filename);
        $this->assertAuthorityPromotion($expectedAuthority, $nextAuthority);

        return $this->authorityPromotionCommandFor(
            stateDirectory: $stateDirectory,
            filename: $filename,
            expectedAuthority: $expectedAuthority,
            nextAuthority: $nextAuthority,
        );
    }

    public function rollbackCommandForRequiringPredecessorAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
        bool $allowInitialOrPreWriteReconciliation = false,
        bool $allowMissingArtifactNoop = false,
    ): string {
        $this->assertRollbackAuthority($mutation, $predecessorAuthority, $rolledBackAuthority);

        return $this->commandFor(
            mutation: $mutation,
            rollback: true,
            requiredAuthority: $predecessorAuthority,
            nextAuthority: $rolledBackAuthority,
            allowMissingArtifactNoop: $allowMissingArtifactNoop,
            allowAuthorityAbsence: $allowInitialOrPreWriteReconciliation,
        );
    }

    public function reconcileRolledBackWriterAuthorityCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        $this->assertRollbackAuthority($mutation, $predecessorAuthority, $rolledBackAuthority);

        return $this->rolledBackAuthorityReconciliationCommandFor(
            mutation: $mutation,
            predecessorAuthority: $predecessorAuthority,
            rolledBackAuthority: $rolledBackAuthority,
        );
    }

    private function commandFor(
        ManagedTraefikDocumentMutation $mutation,
        bool $rollback,
        ?ManagedTraefikDocumentWriterAuthority $requiredAuthority = null,
        ?ManagedTraefikDocumentWriterAuthority $nextAuthority = null,
        bool $allowMissingArtifactNoop = false,
        bool $allowAuthorityBootstrap = false,
        bool $allowAuthorityAbsence = false,
    ): string {
        $expectedSidecar = $mutation->expectedSidecar();
        $authorityMode = $requiredAuthority === null
            ? 'none'
            : ($nextAuthority === null ? 'require' : 'rollback');
        $requiredAuthority = $requiredAuthority?->toJson();
        $nextAuthority = $nextAuthority?->toJson();

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'filename='.escapeshellarg($mutation->filename),
            'operation_id='.escapeshellarg($mutation->operationId),
            'revision='.escapeshellarg((string) $mutation->revision),
            'mode='.escapeshellarg($rollback ? 'rollback' : 'write'),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'authority_path='.escapeshellarg($mutation->writerAuthorityPath()),
            'authority_mode='.escapeshellarg($authorityMode),
            'authority_required_base64='.escapeshellarg($requiredAuthority === null ? 'absent' : base64_encode($requiredAuthority)),
            'authority_next_base64='.escapeshellarg($nextAuthority === null ? 'absent' : base64_encode($nextAuthority)),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'allow_authority_bootstrap='.escapeshellarg($allowAuthorityBootstrap ? 'true' : 'false'),
            'allow_authority_absence='.escapeshellarg($allowAuthorityAbsence ? 'true' : 'false'),
            'allow_missing_artifact_noop='.escapeshellarg($allowMissingArtifactNoop ? 'true' : 'false'),
            'original_expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'original_replacement_document_sha='.escapeshellarg($mutation->replacementSha256()),
            'original_expected_sidecar_base64='.escapeshellarg($expectedSidecar === null ? 'absent' : base64_encode($expectedSidecar)),
            'original_replacement_sidecar_base64='.escapeshellarg(base64_encode($mutation->replacementSidecar())),
            'original_replacement_payload_base64='.escapeshellarg(base64_encode($mutation->replacementBytes)),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'journal_magic='.escapeshellarg(self::JOURNAL_MAGIC),
            'applied_output='.escapeshellarg(self::APPLIED_OUTPUT),
            'rolled_back_output='.escapeshellarg(self::ROLLED_BACK_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { test -d "$1" && test ! -L "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    test ! -L "$1" && test -f "$1" || fail',
            '  fi',
            '}',
            'document_matches() {',
            '  document_candidate=$1',
            '  expected_checksum=$2',
            '  if [ "$expected_checksum" = absent ]; then',
            '    test ! -e "$document_candidate" && test ! -L "$document_candidate"',
            '    return',
            '  fi',
            '  test -e "$document_candidate" && test ! -L "$document_candidate" && test -f "$document_candidate" || return 1',
            '  document_checksum=$(sha256sum "$document_candidate")',
            '  test "${document_checksum%% *}" = "$expected_checksum"',
            '}',
            'sidecar_matches() {',
            '  sidecar_candidate=$1',
            '  expected_sidecar_base64=$2',
            '  expected_sidecar_file=$3',
            '  if [ "$expected_sidecar_base64" = absent ]; then',
            '    test ! -e "$sidecar_candidate" && test ! -L "$sidecar_candidate"',
            '    return',
            '  fi',
            '  test -e "$sidecar_candidate" && test ! -L "$sidecar_candidate" && test -f "$sidecar_candidate" || return 1',
            '  cmp -s "$sidecar_candidate" "$expected_sidecar_file"',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  test -e "$authority_candidate" && test ! -L "$authority_candidate" && test -f "$authority_candidate" || return 1',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'authorize_writer() {',
            '  case "$authority_mode" in',
            '    none)',
            '      test ! -e "$authority_path" && test ! -L "$authority_path" || fail',
            '      ;;',
            '    require)',
            '      if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '        return',
            '      fi',
            '      if [ "$allow_authority_bootstrap" = true ]; then',
            '        atomic_replace "$authority_path" "$authority_required_file" "$state_directory"',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '        return',
            '      fi',
            '      test "$allow_authority_absence" = true || fail',
            '      ;;',
            '    rollback)',
            '      if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '        if authority_matches "$authority_path" "$authority_next_file"; then return; fi',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '      else',
            '        test "$allow_authority_absence" = true || fail',
            '      fi',
            '      atomic_replace "$authority_path" "$authority_next_file" "$state_directory"',
            '      authority_matches "$authority_path" "$authority_next_file" || fail',
            '      ;;',
            '    *)',
            '      fail',
            '      ;;',
            '  esac',
            '}',
            'crash_after_authority_if_requested() {',
            '  if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            '}',
            'crash_after_journal_if_requested() {',
            '  if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_JOURNAL:-}" = 1 ]; then exit 75; fi',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_directory=$3',
            '  replacement_stage=$(mktemp "$replacement_directory/.managed-traefik-document.XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$replacement_directory" || fail',
            '}',
            'atomic_remove() {',
            '  removal_target=$1',
            '  removal_directory=$2',
            '  assert_regular_or_absent "$removal_target"',
            '  durable_remote_remove "$removal_target" "$removal_directory" || fail',
            '}',
            'write_record() {',
            '  record_target=$1',
            '  record_mode=$2',
            '  record_expected_document_sha=$3',
            '  record_replacement_document_sha=$4',
            '  record_expected_sidecar_base64=$5',
            '  record_replacement_sidecar_base64=$6',
            '  record_replacement_payload_base64=$7',
            '  {',
            '    printf "%s\\n" "$journal_magic"',
            '    printf "%s\\n" "$record_mode"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$record_expected_document_sha"',
            '    printf "%s\\n" "$record_replacement_document_sha"',
            '    printf "%s\\n" "$record_expected_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_payload_base64"',
            '  } > "$record_target" || fail',
            '}',
            'write_journal() {',
            '  if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '    assert_regular_or_absent "$journal_path"',
            '    cmp -s "$journal_path" "$expected_journal" || fail',
            '    return',
            '  fi',
            '  journal_stage=$(mktemp "$state_directory/.managed-traefik-journal.XXXXXX") || fail',
            '  cp "$expected_journal" "$journal_stage" || fail',
            '  chmod 600 "$journal_stage" || fail',
            '  durable_remote_replace "$journal_stage" "$journal_path" "$state_directory" || fail',
            '}',
            'validate_artifact() {',
            '  assert_regular_or_absent "$artifact_path"',
            '  test -e "$artifact_path" || fail',
            '  exec 8< "$artifact_path" || fail',
            '  IFS= read -r artifact_line_1 <&8 || fail',
            '  IFS= read -r artifact_line_2 <&8 || fail',
            '  IFS= read -r artifact_line_3 <&8 || fail',
            '  IFS= read -r artifact_line_4 <&8 || fail',
            '  IFS= read -r artifact_line_5 <&8 || fail',
            '  IFS= read -r artifact_line_6 <&8 || fail',
            '  IFS= read -r artifact_line_7 <&8 || fail',
            '  IFS= read -r artifact_line_8 <&8 || fail',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; fail; }',
            '  exec 8<&- || fail',
            '  test "$artifact_line_1" = "$artifact_magic" || fail',
            '  test "$artifact_line_2" = "$filename" || fail',
            '  test "$artifact_line_3" = "$operation_id" || fail',
            '  test "$artifact_line_4" = "$revision" || fail',
            '  test "$artifact_line_5" = "$original_expected_document_sha" || fail',
            '  test "$artifact_line_6" = "$original_replacement_document_sha" || fail',
            '  test "$artifact_line_7" = "$original_expected_sidecar_base64" || fail',
            '  artifact_predecessor_payload_base64=$artifact_line_8',
            '  if [ "$original_expected_document_sha" = absent ]; then',
            '    test "$artifact_predecessor_payload_base64" = absent || fail',
            '  else',
            '    test "$artifact_predecessor_payload_base64" != absent || fail',
            '    printf %s "$artifact_predecessor_payload_base64" | base64 -d > "$scratch/predecessor-document" || fail',
            '    artifact_checksum=$(sha256sum "$scratch/predecessor-document")',
            '    test "${artifact_checksum%% *}" = "$original_expected_document_sha" || fail',
            '  fi',
            '}',
            'create_artifact_if_missing() {',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    return',
            '  fi',
            '  artifact_stage=$(mktemp "$state_directory/.managed-traefik-artifact.XXXXXX") || fail',
            '  {',
            '    printf "%s\\n" "$artifact_magic"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$original_expected_document_sha"',
            '    printf "%s\\n" "$original_replacement_document_sha"',
            '    printf "%s\\n" "$original_expected_sidecar_base64"',
            '    if [ "$original_expected_document_sha" = absent ]; then',
            '      printf "%s\\n" absent',
            '    else',
            '      base64 < "$document_path" | tr -d "\\n"',
            '      printf "\\n"',
            '    fi',
            '  } > "$artifact_stage" || fail',
            '  chmod 600 "$artifact_stage" || fail',
            '  durable_remote_replace "$artifact_stage" "$artifact_path" "$state_directory" || fail',
            '  validate_artifact',
            '}',
            'apply_journal() {',
            '  if document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_document_sha" = absent ]; then',
            '      atomic_remove "$document_path" "$dynamic_directory"',
            '    else',
            '      atomic_replace "$document_path" "$replacement_payload_file" "$dynamic_directory"',
            '    fi',
            '    if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_DOCUMENT:-}" = 1 ]; then exit 75; fi',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif [ "$mode" = rollback ] && document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '    if [ "$replacement_document_sha" = absent ]; then',
            '      atomic_remove "$document_path" "$dynamic_directory"',
            '    else',
            '      atomic_replace "$document_path" "$replacement_payload_file" "$dynamic_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '    :',
            '  else',
            '    fail',
            '  fi',
            '  document_matches "$document_path" "$replacement_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file" || fail',
            '  atomic_remove "$journal_path" "$state_directory"',
            '}',
            'load_mutation_files() {',
            '  if [ "$expected_sidecar_base64" = absent ]; then : > "$expected_sidecar_file"; else printf %s "$expected_sidecar_base64" | base64 -d > "$expected_sidecar_file" || fail; fi',
            '  if [ "$replacement_sidecar_base64" = absent ]; then : > "$replacement_sidecar_file"; else printf %s "$replacement_sidecar_base64" | base64 -d > "$replacement_sidecar_file" || fail; fi',
            '  if [ "$replacement_payload_base64" = absent ]; then : > "$replacement_payload_file"; else printf %s "$replacement_payload_base64" | base64 -d > "$replacement_payload_file" || fail; fi',
            '}',
            '',
            'mkdir -p "$dynamic_directory" "$state_directory" || fail',
            'assert_directory "$dynamic_directory"',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-document.XXXXXX") || fail',
            'expected_sidecar_file="$scratch/expected-sidecar"',
            'replacement_sidecar_file="$scratch/replacement-sidecar"',
            'replacement_payload_file="$scratch/replacement-payload"',
            'expected_journal="$scratch/expected-journal"',
            'forward_journal="$scratch/forward-journal"',
            'authority_required_file="$scratch/authority-required"',
            'authority_next_file="$scratch/authority-next"',
            'cleanup() { rm -f "$expected_sidecar_file" "$replacement_sidecar_file" "$replacement_payload_file" "$expected_journal" "$forward_journal" "$authority_required_file" "$authority_next_file" "$scratch/predecessor-document"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'expected_document_sha=$original_expected_document_sha',
            'replacement_document_sha=$original_replacement_document_sha',
            'expected_sidecar_base64=$original_expected_sidecar_base64',
            'replacement_sidecar_base64=$original_replacement_sidecar_base64',
            'replacement_payload_base64=$original_replacement_payload_base64',
            'rollback_without_artifact=false',
            'if [ "$mode" = rollback ]; then',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    expected_document_sha=$original_replacement_document_sha',
            '    replacement_document_sha=$original_expected_document_sha',
            '    expected_sidecar_base64=$original_replacement_sidecar_base64',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=$artifact_predecessor_payload_base64',
            '  else',
            '    test "$allow_missing_artifact_noop" = true || fail',
            '    rollback_without_artifact=true',
            '    replacement_document_sha=$original_expected_document_sha',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=absent',
            '  fi',
            'fi',
            'load_mutation_files',
            'case "$allow_missing_artifact_noop" in true|false) ;; *) fail ;; esac',
            'if [ "$authority_required_base64" = absent ]; then : > "$authority_required_file"; else printf %s "$authority_required_base64" | base64 -d > "$authority_required_file" || fail; fi',
            'if [ "$authority_next_base64" = absent ]; then : > "$authority_next_file"; else printf %s "$authority_next_base64" | base64 -d > "$authority_next_file" || fail; fi',
            'case "$allow_authority_bootstrap" in true|false) ;; *) fail ;; esac',
            'case "$allow_authority_absence" in true|false) ;; *) fail ;; esac',
            'case "$authority_mode" in',
            '  none)',
            '    test "$authority_required_base64" = absent && test "$authority_next_base64" = absent && test "$allow_authority_bootstrap" = false && test "$allow_authority_absence" = false || fail',
            '    ;;',
            '  require)',
            '    test "$authority_required_base64" != absent && test "$authority_next_base64" = absent || fail',
            '    if [ "$allow_authority_bootstrap" = true ] && [ "$allow_authority_absence" = true ]; then fail; fi',
            '    ;;',
            '  rollback)',
            '    test "$mode" = rollback && test "$authority_required_base64" != absent && test "$authority_next_base64" != absent || fail',
            '    test "$allow_authority_bootstrap" = false || fail',
            '    ;;',
            '  *) fail ;;',
            'esac',
            'if [ "$rollback_without_artifact" = true ]; then',
            '  authorize_writer',
            '  test ! -e "$journal_path" && test ! -L "$journal_path" || fail',
            '  document_matches "$document_path" "$original_expected_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$original_expected_sidecar_base64" "$expected_sidecar_file" || fail',
            '  if [ "$original_expected_document_sha" = absent ]; then durable_remote_remove "$document_path" "$dynamic_directory" || fail; else durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail; fi',
            '  if [ "$original_expected_sidecar_base64" = absent ]; then durable_remote_remove "$sidecar_path" "$state_directory" || fail; else durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail; fi',
            '  durable_remote_remove "$journal_path" "$state_directory" || fail',
            '  printf %s "$rolled_back_output"',
            '  exit 0',
            'fi',
            'if [ "$replacement_document_sha" != absent ]; then',
            '  replacement_checksum=$(sha256sum "$replacement_payload_file")',
            '  test "${replacement_checksum%% *}" = "$replacement_document_sha" || fail',
            'fi',
            'write_record "$expected_journal" "$mode" "$expected_document_sha" "$replacement_document_sha" "$expected_sidecar_base64" "$replacement_sidecar_base64" "$replacement_payload_base64"',
            'if [ "$mode" = rollback ]; then',
            '  write_record "$forward_journal" write "$original_expected_document_sha" "$original_replacement_document_sha" "$original_expected_sidecar_base64" "$original_replacement_sidecar_base64" "$original_replacement_payload_base64"',
            'fi',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '  assert_regular_or_absent "$journal_path"',
            '  if cmp -s "$journal_path" "$expected_journal"; then',
            '    if [ "$mode" = write ]; then validate_artifact; fi',
            '    authorize_writer',
            '    crash_after_authority_if_requested',
            '    apply_journal',
            '  elif [ "$mode" = rollback ] && cmp -s "$journal_path" "$forward_journal"; then',
            '    validate_artifact',
            '    authorize_writer',
            '    crash_after_authority_if_requested',
            '    atomic_replace "$journal_path" "$expected_journal" "$state_directory"',
            '    crash_after_journal_if_requested',
            '    apply_journal',
            '  else',
            '    fail',
            '  fi',
            'elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '  if [ "$mode" = write ]; then validate_artifact; fi',
            '  authorize_writer',
            '  crash_after_authority_if_requested',
            'elif document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '  if [ "$mode" = write ] && { [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; }; then validate_artifact; fi',
            '  authorize_writer',
            '  crash_after_authority_if_requested',
            '  if [ "$mode" = write ]; then create_artifact_if_missing; fi',
            '  write_journal',
            '  crash_after_journal_if_requested',
            '  apply_journal',
            'else',
            '  fail',
            'fi',
            'if [ "$replacement_document_sha" = absent ]; then durable_remote_remove "$document_path" "$dynamic_directory" || fail; else durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail; fi',
            'if [ "$replacement_sidecar_base64" = absent ]; then durable_remote_remove "$sidecar_path" "$state_directory" || fail; else durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail; fi',
            'durable_remote_remove "$journal_path" "$state_directory" || fail',
            'if [ "$mode" = rollback ]; then printf %s "$rolled_back_output"; else printf %s "$applied_output"; fi',
        ]);
    }

    private function authorityPromotionCommandFor(
        string $stateDirectory,
        string $filename,
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): string {
        $lockPath = rtrim($stateDirectory, '/').'/.'.$filename.'.lock';
        $authorityPath = rtrim($stateDirectory, '/').'/.'.$filename.'.writer-authority.json';

        return implode("\n", [
            'set -eu',
            'umask 077',
            'state_directory='.escapeshellarg($stateDirectory),
            'lock_path='.escapeshellarg($lockPath),
            'authority_path='.escapeshellarg($authorityPath),
            'expected_authority_base64='.escapeshellarg(base64_encode($expectedAuthority->toJson())),
            'next_authority_base64='.escapeshellarg(base64_encode($nextAuthority->toJson())),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'promoted_output='.escapeshellarg(self::WRITER_AUTHORITY_PROMOTED_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { test -d "$1" && test ! -L "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    test ! -L "$1" && test -f "$1" || fail',
            '  fi',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  test -e "$authority_candidate" && test ! -L "$authority_candidate" && test -f "$authority_candidate" || return 1',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_stage=$(mktemp "$state_directory/.managed-traefik-authority.XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$state_directory" || fail',
            '}',
            '',
            'mkdir -p "$state_directory" || fail',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$authority_path"',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-authority.XXXXXX") || fail',
            'expected_authority_file="$scratch/expected-authority"',
            'next_authority_file="$scratch/next-authority"',
            'cleanup() { rm -f "$expected_authority_file" "$next_authority_file"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'printf %s "$expected_authority_base64" | base64 -d > "$expected_authority_file" || fail',
            'printf %s "$next_authority_base64" | base64 -d > "$next_authority_file" || fail',
            'if authority_matches "$authority_path" "$next_authority_file"; then',
            '  durable_remote_reaffirm "$authority_path" "$state_directory" || fail',
            '  printf %s "$promoted_output"',
            '  exit 0',
            'fi',
            'authority_matches "$authority_path" "$expected_authority_file" || fail',
            'atomic_replace "$authority_path" "$next_authority_file"',
            'authority_matches "$authority_path" "$next_authority_file" || fail',
            'durable_remote_reaffirm "$authority_path" "$state_directory" || fail',
            'if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            'printf %s "$promoted_output"',
        ]);
    }

    private function rolledBackAuthorityReconciliationCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        $expectedSidecar = $mutation->expectedSidecar();
        $reconciledMarker = implode("\n", [
            'coolify-managed-traefik-rollback-reconciliation-v1',
            $mutation->filename,
            $mutation->operationId,
            (string) $mutation->revision,
            $mutation->expectedSha256 ?? 'absent',
            base64_encode($rolledBackAuthority->toJson()),
            '',
        ]);

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'authority_path='.escapeshellarg($mutation->writerAuthorityPath()),
            'reconciled_marker_path='.escapeshellarg(rtrim($mutation->stateDirectory, '/').'/.'.$mutation->filename.'.'.$mutation->operationId.'.r'.$mutation->revision.'.rollback-reconciled'),
            'filename='.escapeshellarg($mutation->filename),
            'operation_id='.escapeshellarg($mutation->operationId),
            'revision='.escapeshellarg((string) $mutation->revision),
            'expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'expected_sidecar_base64='.escapeshellarg($expectedSidecar === null ? 'absent' : base64_encode($expectedSidecar)),
            'predecessor_authority_base64='.escapeshellarg(base64_encode($predecessorAuthority->toJson())),
            'rolled_back_authority_base64='.escapeshellarg(base64_encode($rolledBackAuthority->toJson())),
            'reconciled_marker_base64='.escapeshellarg(base64_encode($reconciledMarker)),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'journal_magic='.escapeshellarg(self::JOURNAL_MAGIC),
            'reconciled_output='.escapeshellarg(self::ROLLED_BACK_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { test -d "$1" && test ! -L "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    test ! -L "$1" && test -f "$1" || fail',
            '  fi',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  test -e "$authority_candidate" && test ! -L "$authority_candidate" && test -f "$authority_candidate" || return 1',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_directory=$3',
            '  replacement_stage=$(mktemp "$replacement_directory/.managed-traefik-reconcile.XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$replacement_directory" || fail',
            '}',
            'atomic_remove() {',
            '  removal_target=$1',
            '  removal_directory=$2',
            '  assert_regular_or_absent "$removal_target"',
            '  durable_remote_remove "$removal_target" "$removal_directory" || fail',
            '}',
            'document_matches() {',
            '  document_checksum=$(sha256sum "$document_path") || return 1',
            '  test "${document_checksum%% *}" = "$1"',
            '}',
            'valid_operation_id() {',
            '  candidate_operation=$1',
            '  test "${#candidate_operation}" -ge 1 && test "${#candidate_operation}" -le 128 || return 1',
            '  case "$candidate_operation" in [a-z0-9]* ) ;; *) return 1 ;; esac',
            '  case "$candidate_operation" in *[!a-z0-9._-]* ) return 1 ;; esac',
            '}',
            'valid_revision() { case "$1" in ""|*[!0-9]*) return 1 ;; *) test "$1" -ge 1 ;; esac; }',
            'valid_sha256() { test "${#1}" -eq 64 && case "$1" in *[!a-f0-9]*) return 1 ;; *) return 0 ;; esac; }',
            'read_artifact() {',
            '  artifact_candidate=$1',
            '  artifact_size=$(wc -c < "$artifact_candidate" | tr -d "[:space:]") || return 1',
            '  valid_revision "$artifact_size" || return 1',
            '  exec 8< "$artifact_candidate" || return 1',
            '  IFS= read -r artifact_line_1 <&8 || return 1',
            '  IFS= read -r artifact_line_2 <&8 || return 1',
            '  IFS= read -r artifact_line_3 <&8 || return 1',
            '  IFS= read -r artifact_line_4 <&8 || return 1',
            '  IFS= read -r artifact_line_5 <&8 || return 1',
            '  IFS= read -r artifact_line_6 <&8 || return 1',
            '  IFS= read -r artifact_line_7 <&8 || return 1',
            '  IFS= read -r artifact_line_8 <&8 || return 1',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; return 1; }',
            '  exec 8<&- || return 1',
            '  test "$artifact_line_1" = "$artifact_magic" || return 1',
            '  test "$artifact_line_2" = "$filename" || return 1',
            '  test "$artifact_line_5" = "$expected_document_sha" || return 1',
            '  test "$artifact_line_7" = "$expected_sidecar_base64" || return 1',
            '  valid_operation_id "$artifact_line_3" || return 1',
            '  valid_revision "$artifact_line_4" || return 1',
            '  valid_sha256 "$artifact_line_6" || return 1',
            '  printf %s "$artifact_line_8" | base64 -d > "$candidate_predecessor_file" || return 1',
            '  predecessor_checksum=$(sha256sum "$candidate_predecessor_file") || return 1',
            '  test "${predecessor_checksum%% *}" = "$expected_document_sha" || return 1',
            '  printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$artifact_line_3" "$artifact_line_4" "$artifact_line_6" > "$candidate_sidecar_file" || return 1',
            '}',
            'validate_pending_journal() {',
            '  journal_size=$(wc -c < "$journal_path" | tr -d "[:space:]") || fail',
            '  valid_revision "$journal_size" || fail',
            '  exec 7< "$journal_path" || fail',
            '  IFS= read -r journal_line_1 <&7 || fail',
            '  IFS= read -r journal_line_2 <&7 || fail',
            '  IFS= read -r journal_line_3 <&7 || fail',
            '  IFS= read -r journal_line_4 <&7 || fail',
            '  IFS= read -r journal_line_5 <&7 || fail',
            '  IFS= read -r journal_line_6 <&7 || fail',
            '  IFS= read -r journal_line_7 <&7 || fail',
            '  IFS= read -r journal_line_8 <&7 || fail',
            '  IFS= read -r journal_line_9 <&7 || fail',
            '  IFS= read -r journal_line_10 <&7 || fail',
            '  IFS= read -r journal_extra <&7 && { : "$journal_extra"; fail; }',
            '  exec 7<&- || fail',
            '  test "$journal_line_1" = "$journal_magic" || fail',
            '  test "$journal_line_3" = "$filename" || fail',
            '  valid_operation_id "$journal_line_4" || fail',
            '  valid_revision "$journal_line_5" || fail',
            '  journal_operation=$journal_line_4',
            '  journal_revision=$journal_line_5',
            '  case "$journal_line_2" in',
            '    write)',
            '      test "$journal_line_6" = "$expected_document_sha" || fail',
            '      test "$journal_line_8" = "$expected_sidecar_base64" || fail',
            '      valid_sha256 "$journal_line_7" || fail',
            '      journal_successor_sha=$journal_line_7',
            '      printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$journal_operation" "$journal_revision" "$journal_successor_sha" > "$journal_sidecar_file" || fail',
            '      test "$(base64 < "$journal_sidecar_file" | tr -d "\\n")" = "$journal_line_9" || fail',
            '      printf %s "$journal_line_10" | base64 -d > "$successor_document_file" || fail',
            '      journal_payload_checksum=$(sha256sum "$successor_document_file") || fail',
            '      test "${journal_payload_checksum%% *}" = "$journal_successor_sha" || fail',
            '      ;;',
            '    rollback)',
            '      valid_sha256 "$journal_line_6" || fail',
            '      test "$journal_line_7" = "$expected_document_sha" || fail',
            '      test "$journal_line_9" = "$expected_sidecar_base64" || fail',
            '      journal_successor_sha=$journal_line_6',
            '      printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$journal_operation" "$journal_revision" "$journal_successor_sha" > "$journal_sidecar_file" || fail',
            '      test "$(base64 < "$journal_sidecar_file" | tr -d "\\n")" = "$journal_line_8" || fail',
            '      printf %s "$journal_line_10" | base64 -d > "$predecessor_document_file" || fail',
            '      journal_payload_checksum=$(sha256sum "$predecessor_document_file") || fail',
            '      test "${journal_payload_checksum%% *}" = "$expected_document_sha" || fail',
            '      ;;',
            '    *) fail ;;',
            '  esac',
            '}',
            '',
            'assert_directory "$dynamic_directory"',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$reconciled_marker_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$reconciled_marker_path"',
            'test "$expected_document_sha" != absent || fail',
            'test -e "$document_path" && test ! -L "$document_path" && test -f "$document_path" || fail',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-authority.XXXXXX") || fail',
            'expected_sidecar_file="$scratch/expected-sidecar"',
            'successor_sidecar_file="$scratch/successor-sidecar"',
            'predecessor_authority_file="$scratch/predecessor-authority"',
            'rolled_back_authority_file="$scratch/rolled-back-authority"',
            'predecessor_document_file="$scratch/predecessor-document"',
            'successor_document_file="$scratch/successor-document"',
            'candidate_predecessor_file="$scratch/candidate-predecessor"',
            'candidate_sidecar_file="$scratch/candidate-sidecar"',
            'journal_sidecar_file="$scratch/journal-sidecar"',
            'reconciled_marker_file="$scratch/reconciled-marker"',
            'cleanup() { rm -f "$expected_sidecar_file" "$successor_sidecar_file" "$predecessor_authority_file" "$rolled_back_authority_file" "$predecessor_document_file" "$successor_document_file" "$candidate_predecessor_file" "$candidate_sidecar_file" "$journal_sidecar_file" "$reconciled_marker_file"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'test "$expected_sidecar_base64" != absent || fail',
            'printf %s "$expected_sidecar_base64" | base64 -d > "$expected_sidecar_file" || fail',
            'printf %s "$predecessor_authority_base64" | base64 -d > "$predecessor_authority_file" || fail',
            'printf %s "$rolled_back_authority_base64" | base64 -d > "$rolled_back_authority_file" || fail',
            'printf %s "$reconciled_marker_base64" | base64 -d > "$reconciled_marker_file" || fail',
            'if ! authority_matches "$authority_path" "$rolled_back_authority_file"; then',
            '  if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '  authority_matches "$authority_path" "$predecessor_authority_file" || fail',
            '  fi',
            '  atomic_replace "$authority_path" "$rolled_back_authority_file" "$state_directory"',
            'fi',
            'authority_matches "$authority_path" "$rolled_back_authority_file" || fail',
            'durable_remote_reaffirm "$authority_path" "$state_directory" || fail',
            'if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            'if [ -e "$reconciled_marker_path" ] || [ -L "$reconciled_marker_path" ]; then',
            '  cmp -s "$reconciled_marker_path" "$reconciled_marker_file" || fail',
            '  test ! -e "$journal_path" && test ! -L "$journal_path" || fail',
            '  document_matches "$expected_document_sha" || fail',
            '  cmp -s "$sidecar_path" "$expected_sidecar_file" || fail',
            '  durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail',
            '  durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail',
            '  durable_remote_reaffirm "$reconciled_marker_path" "$state_directory" || fail',
            '  durable_remote_remove "$journal_path" "$state_directory" || fail',
            '  printf %s "$reconciled_output"',
            '  exit 0',
            'fi',
            'journal_present=false',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then validate_pending_journal; journal_present=true; fi',
            'if document_matches "$expected_document_sha" && cmp -s "$sidecar_path" "$expected_sidecar_file" && [ "$journal_present" = false ]; then',
            '  atomic_replace "$reconciled_marker_path" "$reconciled_marker_file" "$state_directory"',
            '  printf %s "$reconciled_output"',
            '  exit 0',
            'fi',
            'live_document_checksum=$(sha256sum "$document_path") || fail',
            'live_document_sha=${live_document_checksum%% *}',
            'selected_artifact=false',
            'for artifact_candidate in "$state_directory"/."$filename".*.r*.rollback; do',
            '  test -e "$artifact_candidate" || continue',
            '  test ! -L "$artifact_candidate" && test -f "$artifact_candidate" || continue',
            '  read_artifact "$artifact_candidate" || continue',
            '  if [ "$journal_present" = true ]; then',
            '    test "$artifact_line_3" = "$journal_operation" && test "$artifact_line_4" = "$journal_revision" && test "$artifact_line_6" = "$journal_successor_sha" || continue',
            '  fi',
            '  if { [ "$journal_present" = true ] && { test "$live_document_sha" = "$expected_document_sha" || test "$live_document_sha" = "$artifact_line_6"; } && { cmp -s "$sidecar_path" "$expected_sidecar_file" || cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; } || { test "$live_document_sha" = "$artifact_line_6" && { cmp -s "$sidecar_path" "$expected_sidecar_file" || cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; } || { test "$live_document_sha" = "$expected_document_sha" && cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; then',
            '    cp "$candidate_predecessor_file" "$predecessor_document_file" || fail',
            '    cp "$candidate_sidecar_file" "$successor_sidecar_file" || fail',
            '    selected_artifact=true',
            '    break',
            '  fi',
            'done',
            'test "$selected_artifact" = true || fail',
            'if ! document_matches "$expected_document_sha"; then atomic_replace "$document_path" "$predecessor_document_file" "$dynamic_directory"; fi',
            'if ! cmp -s "$sidecar_path" "$expected_sidecar_file"; then atomic_replace "$sidecar_path" "$expected_sidecar_file" "$state_directory"; fi',
            'document_matches "$expected_document_sha" || fail',
            'cmp -s "$sidecar_path" "$expected_sidecar_file" || fail',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then atomic_remove "$journal_path" "$state_directory"; fi',
            'atomic_replace "$reconciled_marker_path" "$reconciled_marker_file" "$state_directory"',
            'durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail',
            'durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail',
            'durable_remote_reaffirm "$reconciled_marker_path" "$state_directory" || fail',
            'durable_remote_remove "$journal_path" "$state_directory" || fail',
            'printf %s "$reconciled_output"',
        ]);
    }

    private function assertDocumentWriteAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $activeAuthority,
        bool $allowBootstrap,
    ): void {
        if ($allowBootstrap) {
            if ($activeAuthority->epoch !== 1 || ! $activeAuthority->matchesPredecessor($mutation)) {
                throw new InvalidArgumentException('Managed Traefik document writer authority bootstrap is limited to the exact initial epoch-one predecessor authority.');
            }

            return;
        }

        if (! $activeAuthority->matchesPredecessor($mutation)) {
            throw new InvalidArgumentException('The managed Traefik document write must require the exact active predecessor authority.');
        }
    }

    private function assertAuthorityPromotion(
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): void {
        if ($nextAuthority->epoch !== $expectedAuthority->epoch + 1) {
            throw new InvalidArgumentException('A managed Traefik document writer authority promotion must advance exactly one epoch.');
        }
    }

    private function assertWriterAuthorityContext(string $stateDirectory, string $filename): void
    {
        if (! str_starts_with($stateDirectory, '/') || str_contains($stateDirectory, "\0")) {
            throw new InvalidArgumentException('The managed Traefik document writer authority state directory must be an absolute NUL-free path.');
        }

        if (basename($filename) !== $filename
            || preg_match('/\A[a-z0-9][a-z0-9.-]{0,127}\.ya?ml\z/D', $filename) !== 1) {
            throw new InvalidArgumentException('The managed Traefik document writer authority filename is invalid.');
        }
    }

    private function assertRollbackAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): void {
        if (! $predecessorAuthority->matchesPredecessor($mutation)) {
            throw new InvalidArgumentException('The managed Traefik document rollback must require the exact predecessor authority and cannot downgrade a successor authority.');
        }
        if ($rolledBackAuthority->epoch !== $predecessorAuthority->epoch + 1
            || ! hash_equals($rolledBackAuthority->operationId, $mutation->operationId)
            || ! $rolledBackAuthority->matchesPredecessorDocument($mutation)
            || ! $rolledBackAuthority->hasSameWriterIdentityAs($predecessorAuthority)) {
            throw new InvalidArgumentException('The managed Traefik document rollback authority must fence the exact generation attempt while preserving its predecessor writer.');
        }
    }
}
