<?php

namespace App\Actions\Proxy\ControlPlane;

use Lorisleiva\Actions\Concerns\AsAction;

final class ManagedTraefikDocumentWriter
{
    use AsAction;

    public const APPLIED_OUTPUT = 'coolify-managed-traefik-document:applied';

    public const ROLLED_BACK_OUTPUT = 'coolify-managed-traefik-document:rolled-back';

    private const ARTIFACT_MAGIC = 'coolify-managed-traefik-document-rollback-v1';

    private const JOURNAL_MAGIC = 'coolify-managed-traefik-document-journal-v1';

    public function writeCommandFor(ManagedTraefikDocumentMutation $mutation): string
    {
        return $this->commandFor($mutation, false);
    }

    public function rollbackCommandFor(ManagedTraefikDocumentMutation $mutation): string
    {
        return $this->commandFor($mutation, true);
    }

    private function commandFor(ManagedTraefikDocumentMutation $mutation, bool $rollback): string
    {
        $expectedSidecar = $mutation->expectedSidecar();

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'filename='.escapeshellarg($mutation->filename),
            'operation_id='.escapeshellarg($mutation->operationId),
            'revision='.escapeshellarg((string) $mutation->revision),
            'mode='.escapeshellarg($rollback ? 'rollback' : 'write'),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'original_expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'original_replacement_document_sha='.escapeshellarg($mutation->replacementSha256()),
            'original_expected_sidecar_base64='.escapeshellarg($expectedSidecar === null ? 'absent' : base64_encode($expectedSidecar)),
            'original_replacement_sidecar_base64='.escapeshellarg(base64_encode($mutation->replacementSidecar())),
            'original_replacement_payload_base64='.escapeshellarg(base64_encode($mutation->replacementBytes)),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'journal_magic='.escapeshellarg(self::JOURNAL_MAGIC),
            'applied_output='.escapeshellarg(self::APPLIED_OUTPUT),
            'rolled_back_output='.escapeshellarg(self::ROLLED_BACK_OUTPUT),
            '',
            'fail() { exit 1; }',
            'assert_directory() { test -d "$1" && test ! -L "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    test ! -L "$1" && test -f "$1" || fail',
            '  fi',
            '}',
            'document_matches() {',
            '  document_candidate=$1',
            '  expected_checksum=$2',
            '  if [ "$expected_checksum" = absent ]; then',
            '    test ! -e "$document_candidate" && test ! -L "$document_candidate"',
            '    return',
            '  fi',
            '  test -e "$document_candidate" && test ! -L "$document_candidate" && test -f "$document_candidate" || return 1',
            '  document_checksum=$(sha256sum "$document_candidate")',
            '  test "${document_checksum%% *}" = "$expected_checksum"',
            '}',
            'sidecar_matches() {',
            '  sidecar_candidate=$1',
            '  expected_sidecar_base64=$2',
            '  expected_sidecar_file=$3',
            '  if [ "$expected_sidecar_base64" = absent ]; then',
            '    test ! -e "$sidecar_candidate" && test ! -L "$sidecar_candidate"',
            '    return',
            '  fi',
            '  test -e "$sidecar_candidate" && test ! -L "$sidecar_candidate" && test -f "$sidecar_candidate" || return 1',
            '  cmp -s "$sidecar_candidate" "$expected_sidecar_file"',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_directory=$3',
            '  replacement_stage=$(mktemp "$replacement_directory/.managed-traefik-document.XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  sync -f "$replacement_stage" || fail',
            '  mv -f "$replacement_stage" "$replacement_target" || fail',
            '  sync -f "$replacement_directory" || fail',
            '}',
            'atomic_remove() {',
            '  removal_target=$1',
            '  removal_directory=$2',
            '  assert_regular_or_absent "$removal_target"',
            '  rm -f "$removal_target" || fail',
            '  sync -f "$removal_directory" || fail',
            '}',
            'write_record() {',
            '  record_target=$1',
            '  record_mode=$2',
            '  record_expected_document_sha=$3',
            '  record_replacement_document_sha=$4',
            '  record_expected_sidecar_base64=$5',
            '  record_replacement_sidecar_base64=$6',
            '  record_replacement_payload_base64=$7',
            '  {',
            '    printf "%s\\n" "$journal_magic"',
            '    printf "%s\\n" "$record_mode"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$record_expected_document_sha"',
            '    printf "%s\\n" "$record_replacement_document_sha"',
            '    printf "%s\\n" "$record_expected_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_payload_base64"',
            '  } > "$record_target" || fail',
            '}',
            'write_journal() {',
            '  if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '    assert_regular_or_absent "$journal_path"',
            '    cmp -s "$journal_path" "$expected_journal" || fail',
            '    return',
            '  fi',
            '  journal_stage=$(mktemp "$state_directory/.managed-traefik-journal.XXXXXX") || fail',
            '  cp "$expected_journal" "$journal_stage" || fail',
            '  chmod 600 "$journal_stage" || fail',
            '  sync -f "$journal_stage" || fail',
            '  mv -f "$journal_stage" "$journal_path" || fail',
            '  sync -f "$state_directory" || fail',
            '}',
            'validate_artifact() {',
            '  assert_regular_or_absent "$artifact_path"',
            '  test -e "$artifact_path" || fail',
            '  exec 8< "$artifact_path" || fail',
            '  IFS= read -r artifact_line_1 <&8 || fail',
            '  IFS= read -r artifact_line_2 <&8 || fail',
            '  IFS= read -r artifact_line_3 <&8 || fail',
            '  IFS= read -r artifact_line_4 <&8 || fail',
            '  IFS= read -r artifact_line_5 <&8 || fail',
            '  IFS= read -r artifact_line_6 <&8 || fail',
            '  IFS= read -r artifact_line_7 <&8 || fail',
            '  IFS= read -r artifact_line_8 <&8 || fail',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; fail; }',
            '  exec 8<&- || fail',
            '  test "$artifact_line_1" = "$artifact_magic" || fail',
            '  test "$artifact_line_2" = "$filename" || fail',
            '  test "$artifact_line_3" = "$operation_id" || fail',
            '  test "$artifact_line_4" = "$revision" || fail',
            '  test "$artifact_line_5" = "$original_expected_document_sha" || fail',
            '  test "$artifact_line_6" = "$original_replacement_document_sha" || fail',
            '  test "$artifact_line_7" = "$original_expected_sidecar_base64" || fail',
            '  artifact_predecessor_payload_base64=$artifact_line_8',
            '  if [ "$original_expected_document_sha" = absent ]; then',
            '    test "$artifact_predecessor_payload_base64" = absent || fail',
            '  else',
            '    test "$artifact_predecessor_payload_base64" != absent || fail',
            '    printf %s "$artifact_predecessor_payload_base64" | base64 -d > "$scratch/predecessor-document" || fail',
            '    artifact_checksum=$(sha256sum "$scratch/predecessor-document")',
            '    test "${artifact_checksum%% *}" = "$original_expected_document_sha" || fail',
            '  fi',
            '}',
            'create_artifact_if_missing() {',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    return',
            '  fi',
            '  artifact_stage=$(mktemp "$state_directory/.managed-traefik-artifact.XXXXXX") || fail',
            '  {',
            '    printf "%s\\n" "$artifact_magic"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$original_expected_document_sha"',
            '    printf "%s\\n" "$original_replacement_document_sha"',
            '    printf "%s\\n" "$original_expected_sidecar_base64"',
            '    if [ "$original_expected_document_sha" = absent ]; then',
            '      printf "%s\\n" absent',
            '    else',
            '      base64 < "$document_path" | tr -d "\\n"',
            '      printf "\\n"',
            '    fi',
            '  } > "$artifact_stage" || fail',
            '  chmod 600 "$artifact_stage" || fail',
            '  sync -f "$artifact_stage" || fail',
            '  mv -f "$artifact_stage" "$artifact_path" || fail',
            '  sync -f "$state_directory" || fail',
            '  validate_artifact',
            '}',
            'apply_journal() {',
            '  if document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_document_sha" = absent ]; then',
            '      atomic_remove "$document_path" "$dynamic_directory"',
            '    else',
            '      atomic_replace "$document_path" "$replacement_payload_file" "$dynamic_directory"',
            '    fi',
            '    if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_DOCUMENT:-}" = 1 ]; then exit 75; fi',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '    :',
            '  else',
            '    fail',
            '  fi',
            '  document_matches "$document_path" "$replacement_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file" || fail',
            '  atomic_remove "$journal_path" "$state_directory"',
            '}',
            '',
            'mkdir -p "$dynamic_directory" "$state_directory" || fail',
            'assert_directory "$dynamic_directory"',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-document.XXXXXX") || fail',
            'expected_sidecar_file="$scratch/expected-sidecar"',
            'replacement_sidecar_file="$scratch/replacement-sidecar"',
            'replacement_payload_file="$scratch/replacement-payload"',
            'expected_journal="$scratch/expected-journal"',
            'cleanup() { rm -f "$expected_sidecar_file" "$replacement_sidecar_file" "$replacement_payload_file" "$expected_journal" "$scratch/predecessor-document"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'expected_document_sha=$original_expected_document_sha',
            'replacement_document_sha=$original_replacement_document_sha',
            'expected_sidecar_base64=$original_expected_sidecar_base64',
            'replacement_sidecar_base64=$original_replacement_sidecar_base64',
            'replacement_payload_base64=$original_replacement_payload_base64',
            'rollback_without_artifact=false',
            'if [ "$mode" = rollback ]; then',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    expected_document_sha=$original_replacement_document_sha',
            '    replacement_document_sha=$original_expected_document_sha',
            '    expected_sidecar_base64=$original_replacement_sidecar_base64',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=$artifact_predecessor_payload_base64',
            '  else',
            '    rollback_without_artifact=true',
            '    replacement_document_sha=$original_expected_document_sha',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=absent',
            '  fi',
            'fi',
            'if [ "$expected_sidecar_base64" = absent ]; then : > "$expected_sidecar_file"; else printf %s "$expected_sidecar_base64" | base64 -d > "$expected_sidecar_file" || fail; fi',
            'if [ "$replacement_sidecar_base64" = absent ]; then : > "$replacement_sidecar_file"; else printf %s "$replacement_sidecar_base64" | base64 -d > "$replacement_sidecar_file" || fail; fi',
            'if [ "$replacement_payload_base64" = absent ]; then : > "$replacement_payload_file"; else printf %s "$replacement_payload_base64" | base64 -d > "$replacement_payload_file" || fail; fi',
            'if [ "$rollback_without_artifact" = true ]; then',
            '  test ! -e "$journal_path" && test ! -L "$journal_path" || fail',
            '  document_matches "$document_path" "$original_expected_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$original_expected_sidecar_base64" "$expected_sidecar_file" || fail',
            '  printf %s "$rolled_back_output"',
            '  exit 0',
            'fi',
            'if [ "$replacement_document_sha" != absent ]; then',
            '  replacement_checksum=$(sha256sum "$replacement_payload_file")',
            '  test "${replacement_checksum%% *}" = "$replacement_document_sha" || fail',
            'fi',
            'write_record "$expected_journal" "$mode" "$expected_document_sha" "$replacement_document_sha" "$expected_sidecar_base64" "$replacement_sidecar_base64" "$replacement_payload_base64"',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '  assert_regular_or_absent "$journal_path"',
            '  cmp -s "$journal_path" "$expected_journal" || fail',
            '  apply_journal',
            'elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '  if [ "$mode" = write ]; then validate_artifact; fi',
            'elif document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '  if [ "$mode" = write ]; then create_artifact_if_missing; fi',
            '  write_journal',
            '  apply_journal',
            'else',
            '  fail',
            'fi',
            'if [ "$mode" = rollback ]; then printf %s "$rolled_back_output"; else printf %s "$applied_output"; fi',
        ]);
    }
}
