<?php

namespace App\Actions\Proxy\ControlPlane;

use App\Actions\Proxy\DurableRemoteArtifact;
use InvalidArgumentException;
use Lorisleiva\Actions\Concerns\AsAction;

final class ManagedTraefikDocumentWriter
{
    use AsAction;

    public const APPLIED_OUTPUT = 'coolify-managed-traefik-document:applied';

    public const ROLLED_BACK_OUTPUT = 'coolify-managed-traefik-document:rolled-back';

    public const ENROLLMENT_ROLLBACK_FINALIZED_OUTPUT = 'coolify-managed-traefik-document:enrollment-rollback-finalized';

    public const ENROLLMENT_ROLLBACK_PENDING_OUTPUT = 'coolify-managed-traefik-document:enrollment-rollback-pending';

    public const ENROLLMENT_ROLLBACK_CLEANUP_PENDING_OUTPUT = 'coolify-managed-traefik-document:enrollment-rollback-cleanup-pending';

    public const WRITER_AUTHORITY_PROMOTED_OUTPUT = 'coolify-managed-traefik-writer-authority:promoted';

    private const ARTIFACT_MAGIC = 'coolify-managed-traefik-document-rollback-v1';

    private const JOURNAL_MAGIC = 'coolify-managed-traefik-document-journal-v1';

    public function rollbackArtifactFor(
        ManagedTraefikDocumentMutation $mutation,
        ?string $predecessorBytes,
    ): string {
        if (($predecessorBytes === null) !== ($mutation->expectedSha256 === null)
            || ($predecessorBytes !== null
                && ! hash_equals($mutation->expectedSha256 ?? '', hash('sha256', $predecessorBytes)))) {
            throw new InvalidArgumentException('The managed Traefik rollback artifact predecessor does not match its mutation.');
        }

        return implode("\n", [
            self::ARTIFACT_MAGIC,
            $mutation->filename,
            $mutation->operationId,
            (string) $mutation->revision,
            $mutation->expectedSha256 ?? 'absent',
            $mutation->replacementSha256(),
            $mutation->expectedSidecar() === null ? 'absent' : base64_encode($mutation->expectedSidecar()),
            $predecessorBytes === null ? 'absent' : base64_encode($predecessorBytes),
            '',
        ]);
    }

    public function writeCommandFor(ManagedTraefikDocumentMutation $mutation): string
    {
        return $this->commandFor($mutation, false);
    }

    public function rollbackCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        bool $allowMissingArtifactNoop = false,
    ): string {
        return $this->commandFor(
            mutation: $mutation,
            rollback: true,
            allowMissingArtifactNoop: $allowMissingArtifactNoop,
        );
    }

    public function writeCommandForRequiringAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $activeAuthority,
        bool $allowBootstrap,
    ): string {
        $this->assertDocumentWriteAuthority($mutation, $activeAuthority, $allowBootstrap);

        return $this->commandFor(
            mutation: $mutation,
            rollback: false,
            requiredAuthority: $activeAuthority,
            allowAuthorityBootstrap: $allowBootstrap,
        );
    }

    public function promoteWriterAuthorityCommandFor(
        string $stateDirectory,
        string $filename,
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): string {
        $this->assertWriterAuthorityContext($stateDirectory, $filename);
        $this->assertAuthorityPromotion($expectedAuthority, $nextAuthority);

        return $this->authorityPromotionCommandFor(
            stateDirectory: $stateDirectory,
            filename: $filename,
            expectedAuthority: $expectedAuthority,
            nextAuthority: $nextAuthority,
        );
    }

    public function rollbackCommandForRequiringPredecessorAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
        bool $allowInitialOrPreWriteReconciliation = false,
        bool $allowMissingArtifactNoop = false,
    ): string {
        $this->assertRollbackAuthority($mutation, $predecessorAuthority, $rolledBackAuthority);

        return $this->commandFor(
            mutation: $mutation,
            rollback: true,
            requiredAuthority: $predecessorAuthority,
            nextAuthority: $rolledBackAuthority,
            allowMissingArtifactNoop: $allowMissingArtifactNoop,
            allowAuthorityAbsence: $allowInitialOrPreWriteReconciliation,
        );
    }

    public function rollbackEnrollmentCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $replacementAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        if (! $replacementAuthority->matchesReplacement($mutation)
            || $rolledBackAuthority->epoch !== $replacementAuthority->epoch + 1
            || ! hash_equals($rolledBackAuthority->operationId, $mutation->operationId)
            || $rolledBackAuthority->dynamicRevision !== $mutation->revision
            || ! hash_equals(
                $rolledBackAuthority->dynamicSha256,
                $mutation->expectedSha256 ?? hash('sha256', ''),
            )
            || ! $rolledBackAuthority->hasSameWriterIdentityAs($replacementAuthority)) {
            throw new InvalidArgumentException('The enrollment rollback authority must fence the exact replacement and predecessor document.');
        }

        return $this->commandFor(
            mutation: $mutation,
            rollback: true,
            requiredAuthority: $replacementAuthority,
            nextAuthority: $rolledBackAuthority,
            allowMissingArtifactNoop: true,
            allowAuthorityAbsence: true,
        );
    }

    public function finalizeEnrollmentRollbackCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        $this->assertEnrollmentRollbackFinalizationAuthority($mutation, $rolledBackAuthority);

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'state_parent_directory='.escapeshellarg(dirname(rtrim($mutation->stateDirectory, '/'))),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'authority_path='.escapeshellarg($mutation->writerAuthorityPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'filename='.escapeshellarg($mutation->filename),
            'operation_id='.escapeshellarg($mutation->operationId),
            'revision='.escapeshellarg((string) $mutation->revision),
            'expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'replacement_document_sha='.escapeshellarg($mutation->replacementSha256()),
            'rolled_back_authority_base64='.escapeshellarg(base64_encode($rolledBackAuthority->toJson())),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'finalized_output='.escapeshellarg(self::ENROLLMENT_ROLLBACK_FINALIZED_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { durable_remote_assert_owned_directory "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || fail',
            '  fi',
            '}',
            'assert_regular() {',
            '  if [ ! -e "$1" ] || [ -L "$1" ]; then fail; fi',
            '  durable_remote_assert_owned_regular "$1" || fail',
            '}',
            'document_matches_predecessor() {',
            '  if [ "$expected_document_sha" = absent ]; then',
            '    test ! -e "$document_path" && test ! -L "$document_path"',
            '    return',
            '  fi',
            '  if [ ! -e "$document_path" ] || [ -L "$document_path" ] || [ ! -f "$document_path" ]; then return 1; fi',
            '  durable_remote_assert_owned_regular "$document_path" || return 1',
            '  document_checksum=$(sha256sum "$document_path") || return 1',
            '  test "${document_checksum%% *}" = "$expected_document_sha"',
            '}',
            'sidecar_is_absent() { test ! -e "$sidecar_path" && test ! -L "$sidecar_path"; }',
            'authority_matches_rollback() {',
            '  assert_regular "$authority_path"',
            '  authority_size=$(wc -c < "$authority_path" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  authority_base64=$(base64 < "$authority_path" | tr -d "\\n") || return 1',
            '  test "$authority_base64" = "$rolled_back_authority_base64"',
            '}',
            'artifact_matches_mutation() {',
            '  assert_regular "$artifact_path"',
            '  exec 8< "$artifact_path" || return 1',
            '  IFS= read -r artifact_line_1 <&8 || return 1',
            '  IFS= read -r artifact_line_2 <&8 || return 1',
            '  IFS= read -r artifact_line_3 <&8 || return 1',
            '  IFS= read -r artifact_line_4 <&8 || return 1',
            '  IFS= read -r artifact_line_5 <&8 || return 1',
            '  IFS= read -r artifact_line_6 <&8 || return 1',
            '  IFS= read -r artifact_line_7 <&8 || return 1',
            '  IFS= read -r artifact_line_8 <&8 || return 1',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; return 1; }',
            '  exec 8<&- || return 1',
            '  test "$artifact_line_1" = "$artifact_magic" || return 1',
            '  test "$artifact_line_2" = "$filename" || return 1',
            '  test "$artifact_line_3" = "$operation_id" || return 1',
            '  test "$artifact_line_4" = "$revision" || return 1',
            '  test "$artifact_line_5" = "$expected_document_sha" || return 1',
            '  test "$artifact_line_6" = "$replacement_document_sha" || return 1',
            '  test "$artifact_line_7" = absent || return 1',
            '  if [ "$expected_document_sha" = absent ]; then',
            '    test "$artifact_line_8" = absent',
            '    return',
            '  fi',
            '  artifact_predecessor_base64=$(base64 < "$document_path" | tr -d "\\n") || return 1',
            '  test "$artifact_line_8" = "$artifact_predecessor_base64"',
            '}',
            'state_contains_only_enrollment_rollback_files() {',
            '  state_file_count=0',
            '  for state_path in "$state_directory"/* "$state_directory"/.*; do',
            '    [ -e "$state_path" ] || [ -L "$state_path" ] || continue',
            '    case "${state_path##*/}" in .|..) continue ;; esac',
            '    case "$state_path" in',
            '      "$authority_path"|"$artifact_path"|"$lock_path") ;;',
            '      *) return 1 ;;',
            '    esac',
            '    durable_remote_assert_owned_regular "$state_path" || return 1',
            '    state_file_count=$((state_file_count + 1))',
            '  done',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    test "$state_file_count" = 3',
            '  else',
            '    test "$state_file_count" = 2',
            '  fi',
            '}',
            'cleanup_owned_writer_scratch() {',
            '  for scratch_path in "$state_directory"/.managed-traefik-document.*; do',
            '    [ -e "$scratch_path" ] || [ -L "$scratch_path" ] || continue',
            '    [ -d "$scratch_path" ] && [ ! -L "$scratch_path" ] || return 1',
            '    durable_remote_assert_owned_directory "$scratch_path" || return 1',
            '    for scratch_child in "$scratch_path"/* "$scratch_path"/.*; do',
            '      [ -e "$scratch_child" ] || [ -L "$scratch_child" ] || continue',
            '      case "${scratch_child##*/}" in .|..) continue ;; esac',
            '      durable_remote_assert_owned_regular "$scratch_child" || return 1',
            '    done',
            '    for scratch_child in "$scratch_path"/* "$scratch_path"/.*; do',
            '      [ -e "$scratch_child" ] || [ -L "$scratch_child" ] || continue',
            '      case "${scratch_child##*/}" in .|..) continue ;; esac',
            '      durable_remote_remove "$scratch_child" "$scratch_path" || return 1',
            '    done',
            '    rmdir "$scratch_path" || return 1',
            '    sync "$state_directory" || return 1',
            '  done',
            '}',
            '',
            'assert_directory "$state_parent_directory"',
            'assert_directory "$dynamic_directory"',
            'assert_regular_or_absent "$document_path"',
            'document_matches_predecessor || fail',
            'if [ ! -e "$state_directory" ] && [ ! -L "$state_directory" ]; then',
            '  sidecar_is_absent || fail',
            '  printf %s "$finalized_output"',
            '  exit 0',
            'fi',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$lock_path"',
            'sidecar_is_absent || fail',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then fail; fi',
            'assert_regular "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9< "$lock_path" || fail',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular "$lock_path"',
            'document_matches_predecessor || fail',
            'sidecar_is_absent || fail',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then fail; fi',
            'cleanup_owned_writer_scratch || fail',
            'state_contains_only_enrollment_rollback_files || fail',
            'authority_matches_rollback || fail',
            'if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then artifact_matches_mutation || fail; fi',
            'if [ "$expected_document_sha" = absent ]; then',
            '  durable_remote_remove "$document_path" "$dynamic_directory" || fail',
            'else',
            '  durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail',
            'fi',
            'durable_remote_remove "$artifact_path" "$state_directory" || fail',
            'durable_remote_remove "$sidecar_path" "$state_directory" || fail',
            'durable_remote_remove "$authority_path" "$state_directory" || fail',
            'durable_remote_remove "$lock_path" "$state_directory" || fail',
            'rmdir "$state_directory" || fail',
            'sync "$state_parent_directory" || fail',
            'printf %s "$finalized_output"',
        ]);
    }

    public function inspectEnrollmentRollbackFinalizationCommandFor(
        ManagedTraefikDocumentMutation $mutation,
    ): string {
        if ($mutation->expectedSidecar() !== null) {
            throw new InvalidArgumentException('Enrollment rollback finalization inspection requires an unmanaged predecessor state.');
        }

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'state_parent_directory='.escapeshellarg(dirname(rtrim($mutation->stateDirectory, '/'))),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'pending_output='.escapeshellarg(self::ENROLLMENT_ROLLBACK_PENDING_OUTPUT),
            'cleanup_pending_output='.escapeshellarg(self::ENROLLMENT_ROLLBACK_CLEANUP_PENDING_OUTPUT),
            'finalized_output='.escapeshellarg(self::ENROLLMENT_ROLLBACK_FINALIZED_OUTPUT),
            '',
            'fail() { exit 1; }',
            'pending() { printf %s "$pending_output"; exit 0; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_trusted_legacy_directory() {',
            '  [ -d "$1" ] && [ ! -L "$1" ] || return 1',
            '  trusted_owner_uid=$(durable_remote_owner_uid "$1") || return 1',
            '  if [ "$trusted_owner_uid" != 0 ] && [ "$trusted_owner_uid" != 9999 ] && [ "$trusted_owner_uid" != "$(id -u)" ]; then return 1; fi',
            '  trusted_permissions=$(durable_remote_permissions "$1") || return 1',
            '  case "$trusted_permissions" in ???|????) ;; *) return 1 ;; esac',
            '  case "$trusted_permissions" in *[!0-7]*) return 1 ;; esac',
            '  trusted_other_permissions=${trusted_permissions#"${trusted_permissions%?}"}',
            '  trusted_owner_group_permissions=${trusted_permissions%?}',
            '  trusted_group_permissions=${trusted_owner_group_permissions#"${trusted_owner_group_permissions%?}"}',
            '  case "${trusted_group_permissions}${trusted_other_permissions}" in *[2367]*) return 1 ;; esac',
            '}',
            'assert_trusted_legacy_regular() {',
            '  [ -f "$1" ] && [ ! -L "$1" ] || return 1',
            '  trusted_owner_uid=$(durable_remote_owner_uid "$1") || return 1',
            '  if [ "$trusted_owner_uid" != 0 ] && [ "$trusted_owner_uid" != 9999 ] && [ "$trusted_owner_uid" != "$(id -u)" ]; then return 1; fi',
            '  [ "$(durable_remote_link_count "$1")" = 1 ]',
            '}',
            'assert_trusted_legacy_directory "$state_parent_directory" || fail',
            'assert_trusted_legacy_directory "$dynamic_directory" || fail',
            'if [ -e "$sidecar_path" ] || [ -L "$sidecar_path" ]; then pending; fi',
            'if [ "$expected_document_sha" = absent ]; then',
            '  if [ -e "$document_path" ] || [ -L "$document_path" ]; then pending; fi',
            'else',
            '  if [ ! -e "$document_path" ] || [ -L "$document_path" ] || [ ! -f "$document_path" ]; then pending; fi',
            '  assert_trusted_legacy_regular "$document_path" || fail',
            '  document_checksum=$(sha256sum "$document_path") || fail',
            '  if [ "${document_checksum%% *}" != "$expected_document_sha" ]; then pending; fi',
            'fi',
            'if [ ! -e "$state_directory" ] && [ ! -L "$state_directory" ]; then',
            '  printf %s "$finalized_output"',
            '  exit 0',
            'fi',
            'assert_trusted_legacy_directory "$state_directory" || pending',
            'cleanup_only=true',
            'for state_path in "$state_directory"/* "$state_directory"/.*; do',
            '  [ -e "$state_path" ] || [ -L "$state_path" ] || continue',
            '  case "${state_path##*/}" in .|..) continue ;; esac',
            '  if [ "$state_path" != "$lock_path" ] || ! assert_trusted_legacy_regular "$state_path"; then cleanup_only=false; fi',
            'done',
            'if [ "$cleanup_only" = true ]; then printf %s "$cleanup_pending_output"; exit 0; fi',
            'pending',
        ]);
    }

    public function finalizePartialEnrollmentRollbackCommandFor(
        ManagedTraefikDocumentMutation $mutation,
    ): string {
        if ($mutation->expectedSidecar() !== null) {
            throw new InvalidArgumentException('Partial enrollment rollback finalization requires an unmanaged predecessor state.');
        }

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'state_parent_directory='.escapeshellarg(dirname(rtrim($mutation->stateDirectory, '/'))),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'finalized_output='.escapeshellarg(self::ENROLLMENT_ROLLBACK_FINALIZED_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_trusted_legacy_directory() {',
            '  [ -d "$1" ] && [ ! -L "$1" ] || return 1',
            '  trusted_owner_uid=$(durable_remote_owner_uid "$1") || return 1',
            '  if [ "$trusted_owner_uid" != 0 ] && [ "$trusted_owner_uid" != 9999 ] && [ "$trusted_owner_uid" != "$(id -u)" ]; then return 1; fi',
            '  trusted_permissions=$(durable_remote_permissions "$1") || return 1',
            '  case "$trusted_permissions" in ???|????) ;; *) return 1 ;; esac',
            '  case "$trusted_permissions" in *[!0-7]*) return 1 ;; esac',
            '  trusted_other_permissions=${trusted_permissions#"${trusted_permissions%?}"}',
            '  trusted_owner_group_permissions=${trusted_permissions%?}',
            '  trusted_group_permissions=${trusted_owner_group_permissions#"${trusted_owner_group_permissions%?}"}',
            '  case "${trusted_group_permissions}${trusted_other_permissions}" in *[2367]*) return 1 ;; esac',
            '}',
            'assert_trusted_legacy_regular() {',
            '  [ -f "$1" ] && [ ! -L "$1" ] || return 1',
            '  trusted_owner_uid=$(durable_remote_owner_uid "$1") || return 1',
            '  if [ "$trusted_owner_uid" != 0 ] && [ "$trusted_owner_uid" != 9999 ] && [ "$trusted_owner_uid" != "$(id -u)" ]; then return 1; fi',
            '  [ "$(durable_remote_link_count "$1")" = 1 ]',
            '}',
            'assert_document_predecessor() {',
            '  if [ "$expected_document_sha" = absent ]; then',
            '    [ ! -e "$document_path" ] && [ ! -L "$document_path" ]',
            '    return',
            '  fi',
            '  assert_trusted_legacy_regular "$document_path" || return 1',
            '  document_checksum=$(sha256sum "$document_path") || return 1',
            '  [ "${document_checksum%% *}" = "$expected_document_sha" ]',
            '}',
            'assert_cleanup_only_state() {',
            '  for state_path in "$state_directory"/* "$state_directory"/.*; do',
            '    [ -e "$state_path" ] || [ -L "$state_path" ] || continue',
            '    case "${state_path##*/}" in .|..) continue ;; esac',
            '    [ "$state_path" = "$lock_path" ] || return 1',
            '    assert_trusted_legacy_regular "$state_path" || return 1',
            '  done',
            '}',
            'assert_trusted_legacy_directory "$state_parent_directory" || fail',
            'assert_trusted_legacy_directory "$dynamic_directory" || fail',
            'assert_trusted_legacy_directory "$state_directory" || fail',
            '[ ! -e "$sidecar_path" ] && [ ! -L "$sidecar_path" ] || fail',
            'assert_document_predecessor || fail',
            'assert_cleanup_only_state || fail',
            'if [ -e "$lock_path" ] || [ -L "$lock_path" ]; then',
            '  assert_trusted_legacy_regular "$lock_path" || fail',
            '  command -v flock >/dev/null 2>&1 || fail',
            '  exec 9< "$lock_path" || fail',
            '  flock -x 9 || fail',
            'fi',
            'assert_cleanup_only_state || fail',
            '[ ! -e "$sidecar_path" ] && [ ! -L "$sidecar_path" ] || fail',
            'assert_document_predecessor || fail',
            'if [ -e "$lock_path" ] || [ -L "$lock_path" ]; then rm -f -- "$lock_path" || fail; fi',
            'rmdir "$state_directory" || fail',
            'sync "$state_parent_directory" || fail',
            'printf %s "$finalized_output"',
        ]);
    }

    public function reconcileRolledBackWriterAuthorityCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        $this->assertRollbackAuthority($mutation, $predecessorAuthority, $rolledBackAuthority);

        return $this->rolledBackAuthorityReconciliationCommandFor(
            mutation: $mutation,
            predecessorAuthority: $predecessorAuthority,
            rolledBackAuthority: $rolledBackAuthority,
        );
    }

    private function commandFor(
        ManagedTraefikDocumentMutation $mutation,
        bool $rollback,
        ?ManagedTraefikDocumentWriterAuthority $requiredAuthority = null,
        ?ManagedTraefikDocumentWriterAuthority $nextAuthority = null,
        bool $allowMissingArtifactNoop = false,
        bool $allowAuthorityBootstrap = false,
        bool $allowAuthorityAbsence = false,
    ): string {
        $expectedSidecar = $mutation->expectedSidecar();
        $authorityMode = $requiredAuthority === null
            ? 'none'
            : ($nextAuthority === null ? 'require' : 'rollback');
        $requiredAuthority = $requiredAuthority?->toJson();
        $nextAuthority = $nextAuthority?->toJson();

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'filename='.escapeshellarg($mutation->filename),
            'operation_id='.escapeshellarg($mutation->operationId),
            'revision='.escapeshellarg((string) $mutation->revision),
            'mode='.escapeshellarg($rollback ? 'rollback' : 'write'),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'authority_path='.escapeshellarg($mutation->writerAuthorityPath()),
            'authority_mode='.escapeshellarg($authorityMode),
            'authority_required_base64='.escapeshellarg($requiredAuthority === null ? 'absent' : base64_encode($requiredAuthority)),
            'authority_next_base64='.escapeshellarg($nextAuthority === null ? 'absent' : base64_encode($nextAuthority)),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'allow_authority_bootstrap='.escapeshellarg($allowAuthorityBootstrap ? 'true' : 'false'),
            'allow_authority_absence='.escapeshellarg($allowAuthorityAbsence ? 'true' : 'false'),
            'allow_missing_artifact_noop='.escapeshellarg($allowMissingArtifactNoop ? 'true' : 'false'),
            'original_expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'original_replacement_document_sha='.escapeshellarg($mutation->replacementSha256()),
            'original_expected_sidecar_base64='.escapeshellarg($expectedSidecar === null ? 'absent' : base64_encode($expectedSidecar)),
            'original_replacement_sidecar_base64='.escapeshellarg(base64_encode($mutation->replacementSidecar())),
            'original_replacement_payload_base64='.escapeshellarg(base64_encode($mutation->replacementBytes)),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'journal_magic='.escapeshellarg(self::JOURNAL_MAGIC),
            'applied_output='.escapeshellarg(self::APPLIED_OUTPUT),
            'rolled_back_output='.escapeshellarg(self::ROLLED_BACK_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { durable_remote_assert_owned_directory "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || fail',
            '  fi',
            '}',
            'file_owner() {',
            '  if stat -c "%u:%g" "$1" >/dev/null 2>&1; then stat -c "%u:%g" "$1"; else stat -f "%u:%g" "$1"; fi',
            '}',
            'file_mode() {',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'normalize_file_visibility() {',
            '  visibility_path=$1',
            '  visibility_owner=$2',
            '  visibility_mode=$3',
            '  durable_remote_assert_owned_regular "$visibility_path" || fail',
            '  if [ "$(id -u)" = 0 ]; then',
            '    chown "$visibility_owner" "$visibility_path" || fail',
            '    test "$(file_owner "$visibility_path")" = "$visibility_owner" || fail',
            '  fi',
            '  chmod "$visibility_mode" "$visibility_path" || fail',
            '  test "$(file_mode "$visibility_path")" = "$visibility_mode" || fail',
            '  durable_remote_reaffirm "$visibility_path" "${visibility_path%/*}" || fail',
            '}',
            'normalize_public_attestor_file() { normalize_file_visibility "$1" 0:9999 640; }',
            'normalize_private_file() { normalize_file_visibility "$1" 0:0 600; }',
            'normalize_target_visibility() {',
            '  case "$1" in',
            '    "$document_path"|"$sidecar_path"|"$authority_path") normalize_public_attestor_file "$1" ;;',
            '    *) normalize_private_file "$1" ;;',
            '  esac',
            '}',
            'normalize_visible_state() {',
            '  if [ -e "$document_path" ]; then normalize_public_attestor_file "$document_path"; fi',
            '  if [ -e "$sidecar_path" ]; then normalize_public_attestor_file "$sidecar_path"; fi',
            '  if [ -e "$authority_path" ]; then normalize_public_attestor_file "$authority_path"; fi',
            '  if [ -e "$lock_path" ]; then normalize_private_file "$lock_path"; fi',
            '  if [ -e "$journal_path" ]; then normalize_private_file "$journal_path"; fi',
            '  if [ -e "$artifact_path" ]; then normalize_private_file "$artifact_path"; fi',
            '}',
            'document_matches() {',
            '  document_candidate=$1',
            '  expected_checksum=$2',
            '  if [ "$expected_checksum" = absent ]; then',
            '    test ! -e "$document_candidate" && test ! -L "$document_candidate"',
            '    return',
            '  fi',
            '  if [ ! -e "$document_candidate" ] || [ -L "$document_candidate" ] || [ ! -f "$document_candidate" ]; then return 1; fi',
            '  document_checksum=$(sha256sum "$document_candidate")',
            '  test "${document_checksum%% *}" = "$expected_checksum"',
            '}',
            'sidecar_matches() {',
            '  sidecar_candidate_path=$1',
            '  sidecar_expected_base64=$2',
            '  sidecar_expected_file=$3',
            '  if [ "$sidecar_expected_base64" = absent ]; then',
            '    test ! -e "$sidecar_candidate_path" && test ! -L "$sidecar_candidate_path"',
            '    return',
            '  fi',
            '  if [ ! -e "$sidecar_candidate_path" ] || [ -L "$sidecar_candidate_path" ] || [ ! -f "$sidecar_candidate_path" ]; then return 1; fi',
            '  cmp -s "$sidecar_candidate_path" "$sidecar_expected_file"',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  if [ ! -e "$authority_candidate" ] || [ -L "$authority_candidate" ] || [ ! -f "$authority_candidate" ]; then return 1; fi',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'authorize_writer() {',
            '  case "$authority_mode" in',
            '    none)',
            '      if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then fail; fi',
            '      ;;',
            '    require)',
            '      if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '        return',
            '      fi',
            '      if [ "$allow_authority_bootstrap" = true ]; then',
            '        atomic_replace "$authority_path" "$authority_required_file" "$state_directory"',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '        return',
            '      fi',
            '      test "$allow_authority_absence" = true || fail',
            '      ;;',
            '    rollback)',
            '      if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '        if authority_matches "$authority_path" "$authority_next_file"; then return; fi',
            '        authority_matches "$authority_path" "$authority_required_file" || fail',
            '      else',
            '        test "$allow_authority_absence" = true || fail',
            '      fi',
            '      atomic_replace "$authority_path" "$authority_next_file" "$state_directory"',
            '      authority_matches "$authority_path" "$authority_next_file" || fail',
            '      ;;',
            '    *)',
            '      fail',
            '      ;;',
            '  esac',
            '}',
            'crash_after_authority_if_requested() {',
            '  if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            '}',
            'crash_after_journal_if_requested() {',
            '  if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_JOURNAL:-}" = 1 ]; then exit 75; fi',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_directory=$3',
            '  replacement_prefix=".managed-traefik-document.${filename}."',
            '  durable_remote_cleanup_owned_regular_prefix "$replacement_directory" "$replacement_prefix" || fail',
            '  replacement_stage=$(mktemp "$replacement_directory/${replacement_prefix}XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$replacement_directory" || fail',
            '  normalize_target_visibility "$replacement_target"',
            '}',
            'atomic_remove() {',
            '  removal_target=$1',
            '  removal_directory=$2',
            '  assert_regular_or_absent "$removal_target"',
            '  durable_remote_remove "$removal_target" "$removal_directory" || fail',
            '}',
            'write_record() {',
            '  record_target=$1',
            '  record_mode=$2',
            '  record_expected_document_sha=$3',
            '  record_replacement_document_sha=$4',
            '  record_expected_sidecar_base64=$5',
            '  record_replacement_sidecar_base64=$6',
            '  record_replacement_payload_base64=$7',
            '  {',
            '    printf "%s\\n" "$journal_magic"',
            '    printf "%s\\n" "$record_mode"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$record_expected_document_sha"',
            '    printf "%s\\n" "$record_replacement_document_sha"',
            '    printf "%s\\n" "$record_expected_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_sidecar_base64"',
            '    printf "%s\\n" "$record_replacement_payload_base64"',
            '  } > "$record_target" || fail',
            '}',
            'write_journal() {',
            '  if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '    assert_regular_or_absent "$journal_path"',
            '    cmp -s "$journal_path" "$expected_journal" || fail',
            '    return',
            '  fi',
            '  journal_prefix=".managed-traefik-journal.${filename}."',
            '  durable_remote_cleanup_owned_regular_prefix "$state_directory" "$journal_prefix" || fail',
            '  journal_stage=$(mktemp "$state_directory/${journal_prefix}XXXXXX") || fail',
            '  cp "$expected_journal" "$journal_stage" || fail',
            '  chmod 600 "$journal_stage" || fail',
            '  durable_remote_replace "$journal_stage" "$journal_path" "$state_directory" || fail',
            '  normalize_private_file "$journal_path"',
            '}',
            'validate_artifact() {',
            '  assert_regular_or_absent "$artifact_path"',
            '  test -e "$artifact_path" || fail',
            '  exec 8< "$artifact_path" || fail',
            '  IFS= read -r artifact_line_1 <&8 || fail',
            '  IFS= read -r artifact_line_2 <&8 || fail',
            '  IFS= read -r artifact_line_3 <&8 || fail',
            '  IFS= read -r artifact_line_4 <&8 || fail',
            '  IFS= read -r artifact_line_5 <&8 || fail',
            '  IFS= read -r artifact_line_6 <&8 || fail',
            '  IFS= read -r artifact_line_7 <&8 || fail',
            '  IFS= read -r artifact_line_8 <&8 || fail',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; fail; }',
            '  exec 8<&- || fail',
            '  test "$artifact_line_1" = "$artifact_magic" || fail',
            '  test "$artifact_line_2" = "$filename" || fail',
            '  test "$artifact_line_3" = "$operation_id" || fail',
            '  test "$artifact_line_4" = "$revision" || fail',
            '  test "$artifact_line_5" = "$original_expected_document_sha" || fail',
            '  test "$artifact_line_6" = "$original_replacement_document_sha" || fail',
            '  test "$artifact_line_7" = "$original_expected_sidecar_base64" || fail',
            '  artifact_predecessor_payload_base64=$artifact_line_8',
            '  if [ "$original_expected_document_sha" = absent ]; then',
            '    test "$artifact_predecessor_payload_base64" = absent || fail',
            '  else',
            '    test "$artifact_predecessor_payload_base64" != absent || fail',
            '    printf %s "$artifact_predecessor_payload_base64" | base64 -d > "$scratch/predecessor-document" || fail',
            '    artifact_checksum=$(sha256sum "$scratch/predecessor-document")',
            '    test "${artifact_checksum%% *}" = "$original_expected_document_sha" || fail',
            '  fi',
            '}',
            'create_artifact_if_missing() {',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    return',
            '  fi',
            '  artifact_prefix=".managed-traefik-artifact.${filename}."',
            '  durable_remote_cleanup_owned_regular_prefix "$state_directory" "$artifact_prefix" || fail',
            '  artifact_stage=$(mktemp "$state_directory/${artifact_prefix}XXXXXX") || fail',
            '  {',
            '    printf "%s\\n" "$artifact_magic"',
            '    printf "%s\\n" "$filename"',
            '    printf "%s\\n" "$operation_id"',
            '    printf "%s\\n" "$revision"',
            '    printf "%s\\n" "$original_expected_document_sha"',
            '    printf "%s\\n" "$original_replacement_document_sha"',
            '    printf "%s\\n" "$original_expected_sidecar_base64"',
            '    if [ "$original_expected_document_sha" = absent ]; then',
            '      printf "%s\\n" absent',
            '    else',
            '      base64 < "$document_path" | tr -d "\\n"',
            '      printf "\\n"',
            '    fi',
            '  } > "$artifact_stage" || fail',
            '  chmod 600 "$artifact_stage" || fail',
            '  durable_remote_replace "$artifact_stage" "$artifact_path" "$state_directory" || fail',
            '  normalize_private_file "$artifact_path"',
            '  validate_artifact',
            '}',
            'apply_journal() {',
            '  if document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_document_sha" = absent ]; then',
            '      atomic_remove "$document_path" "$dynamic_directory"',
            '    else',
            '      atomic_replace "$document_path" "$replacement_payload_file" "$dynamic_directory"',
            '    fi',
            '    if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_DOCUMENT:-}" = 1 ]; then exit 75; fi',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '    if [ "$replacement_sidecar_base64" = absent ]; then',
            '      atomic_remove "$sidecar_path" "$state_directory"',
            '    else',
            '      atomic_replace "$sidecar_path" "$replacement_sidecar_file" "$state_directory"',
            '    fi',
            '  elif [ "$mode" = rollback ] && document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '    if [ "$replacement_document_sha" = absent ]; then',
            '      atomic_remove "$document_path" "$dynamic_directory"',
            '    else',
            '      atomic_replace "$document_path" "$replacement_payload_file" "$dynamic_directory"',
            '    fi',
            '  elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '    :',
            '  else',
            '    fail',
            '  fi',
            '  document_matches "$document_path" "$replacement_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file" || fail',
            '  atomic_remove "$journal_path" "$state_directory"',
            '}',
            'load_mutation_files() {',
            '  if [ "$expected_sidecar_base64" = absent ]; then : > "$expected_sidecar_file"; else printf %s "$expected_sidecar_base64" | base64 -d > "$expected_sidecar_file" || fail; fi',
            '  if [ "$replacement_sidecar_base64" = absent ]; then : > "$replacement_sidecar_file"; else printf %s "$replacement_sidecar_base64" | base64 -d > "$replacement_sidecar_file" || fail; fi',
            '  if [ "$replacement_payload_base64" = absent ]; then : > "$replacement_payload_file"; else printf %s "$replacement_payload_base64" | base64 -d > "$replacement_payload_file" || fail; fi',
            '}',
            '',
            'mkdir -p "$dynamic_directory" "$state_directory" || fail',
            'assert_directory "$dynamic_directory"',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'durable_remote_assert_owned_regular "$lock_path" || fail',
            'normalize_private_file "$lock_path"',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-document.XXXXXX") || fail',
            'expected_sidecar_file="$scratch/expected-sidecar"',
            'replacement_sidecar_file="$scratch/replacement-sidecar"',
            'replacement_payload_file="$scratch/replacement-payload"',
            'expected_journal="$scratch/expected-journal"',
            'forward_journal="$scratch/forward-journal"',
            'authority_required_file="$scratch/authority-required"',
            'authority_next_file="$scratch/authority-next"',
            'cleanup() { rm -f "$expected_sidecar_file" "$replacement_sidecar_file" "$replacement_payload_file" "$expected_journal" "$forward_journal" "$authority_required_file" "$authority_next_file" "$scratch/predecessor-document"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'expected_document_sha=$original_expected_document_sha',
            'replacement_document_sha=$original_replacement_document_sha',
            'expected_sidecar_base64=$original_expected_sidecar_base64',
            'replacement_sidecar_base64=$original_replacement_sidecar_base64',
            'replacement_payload_base64=$original_replacement_payload_base64',
            'rollback_without_artifact=false',
            'if [ "$mode" = rollback ]; then',
            '  if [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; then',
            '    validate_artifact',
            '    expected_document_sha=$original_replacement_document_sha',
            '    replacement_document_sha=$original_expected_document_sha',
            '    expected_sidecar_base64=$original_replacement_sidecar_base64',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=$artifact_predecessor_payload_base64',
            '  else',
            '    test "$allow_missing_artifact_noop" = true || fail',
            '    rollback_without_artifact=true',
            '    replacement_document_sha=$original_expected_document_sha',
            '    replacement_sidecar_base64=$original_expected_sidecar_base64',
            '    replacement_payload_base64=absent',
            '  fi',
            'fi',
            'load_mutation_files',
            'case "$allow_missing_artifact_noop" in true|false) ;; *) fail ;; esac',
            'if [ "$authority_required_base64" = absent ]; then : > "$authority_required_file"; else printf %s "$authority_required_base64" | base64 -d > "$authority_required_file" || fail; fi',
            'if [ "$authority_next_base64" = absent ]; then : > "$authority_next_file"; else printf %s "$authority_next_base64" | base64 -d > "$authority_next_file" || fail; fi',
            'case "$allow_authority_bootstrap" in true|false) ;; *) fail ;; esac',
            'case "$allow_authority_absence" in true|false) ;; *) fail ;; esac',
            'case "$authority_mode" in',
            '  none)',
            '    if ! { test "$authority_required_base64" = absent && test "$authority_next_base64" = absent && test "$allow_authority_bootstrap" = false && test "$allow_authority_absence" = false; }; then fail; fi',
            '    ;;',
            '  require)',
            '    if ! { test "$authority_required_base64" != absent && test "$authority_next_base64" = absent; }; then fail; fi',
            '    if [ "$allow_authority_bootstrap" = true ] && [ "$allow_authority_absence" = true ]; then fail; fi',
            '    ;;',
            '  rollback)',
            '    if ! { test "$mode" = rollback && test "$authority_required_base64" != absent && test "$authority_next_base64" != absent; }; then fail; fi',
            '    test "$allow_authority_bootstrap" = false || fail',
            '    ;;',
            '  *) fail ;;',
            'esac',
            'if [ "$rollback_without_artifact" = true ]; then',
            '  if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then fail; fi',
            '  document_matches "$document_path" "$original_expected_document_sha" || fail',
            '  sidecar_matches "$sidecar_path" "$original_expected_sidecar_base64" "$expected_sidecar_file" || fail',
            '  authorize_writer',
            '  if [ "$original_expected_document_sha" = absent ]; then durable_remote_remove "$document_path" "$dynamic_directory" || fail; else durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail; fi',
            '  if [ "$original_expected_sidecar_base64" = absent ]; then durable_remote_remove "$sidecar_path" "$state_directory" || fail; else durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail; fi',
            '  durable_remote_remove "$journal_path" "$state_directory" || fail',
            '  normalize_visible_state',
            '  printf %s "$rolled_back_output"',
            '  exit 0',
            'fi',
            'if [ "$replacement_document_sha" != absent ]; then',
            '  replacement_checksum=$(sha256sum "$replacement_payload_file")',
            '  test "${replacement_checksum%% *}" = "$replacement_document_sha" || fail',
            'fi',
            'write_record "$expected_journal" "$mode" "$expected_document_sha" "$replacement_document_sha" "$expected_sidecar_base64" "$replacement_sidecar_base64" "$replacement_payload_base64"',
            'if [ "$mode" = rollback ]; then',
            '  write_record "$forward_journal" write "$original_expected_document_sha" "$original_replacement_document_sha" "$original_expected_sidecar_base64" "$original_replacement_sidecar_base64" "$original_replacement_payload_base64"',
            'fi',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then',
            '  assert_regular_or_absent "$journal_path"',
            '  if cmp -s "$journal_path" "$expected_journal"; then',
            '    if [ "$mode" = write ]; then validate_artifact; fi',
            '    authorize_writer',
            '    crash_after_authority_if_requested',
            '    apply_journal',
            '  elif [ "$mode" = rollback ] && cmp -s "$journal_path" "$forward_journal"; then',
            '    validate_artifact',
            '    authorize_writer',
            '    crash_after_authority_if_requested',
            '    atomic_replace "$journal_path" "$expected_journal" "$state_directory"',
            '    crash_after_journal_if_requested',
            '    apply_journal',
            '  else',
            '    fail',
            '  fi',
            'elif document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$replacement_sidecar_base64" "$replacement_sidecar_file"; then',
            '  if [ "$mode" = write ]; then validate_artifact; fi',
            '  authorize_writer',
            '  crash_after_authority_if_requested',
            'elif [ "$mode" = rollback ] && document_matches "$document_path" "$replacement_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '  validate_artifact',
            '  authorize_writer',
            '  crash_after_authority_if_requested',
            '  write_journal',
            '  crash_after_journal_if_requested',
            '  apply_journal',
            'elif document_matches "$document_path" "$expected_document_sha" && sidecar_matches "$sidecar_path" "$expected_sidecar_base64" "$expected_sidecar_file"; then',
            '  if [ "$mode" = write ] && { [ -e "$artifact_path" ] || [ -L "$artifact_path" ]; }; then validate_artifact; fi',
            '  authorize_writer',
            '  crash_after_authority_if_requested',
            '  if [ "$mode" = write ]; then create_artifact_if_missing; fi',
            '  write_journal',
            '  crash_after_journal_if_requested',
            '  apply_journal',
            'else',
            '  fail',
            'fi',
            'if [ "$replacement_document_sha" = absent ]; then durable_remote_remove "$document_path" "$dynamic_directory" || fail; else durable_remote_reaffirm "$document_path" "$dynamic_directory" || fail; fi',
            'if [ "$replacement_sidecar_base64" = absent ]; then durable_remote_remove "$sidecar_path" "$state_directory" || fail; else durable_remote_reaffirm "$sidecar_path" "$state_directory" || fail; fi',
            'durable_remote_remove "$journal_path" "$state_directory" || fail',
            'normalize_visible_state',
            'if [ "$mode" = rollback ]; then printf %s "$rolled_back_output"; else printf %s "$applied_output"; fi',
        ]);
    }

    private function authorityPromotionCommandFor(
        string $stateDirectory,
        string $filename,
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): string {
        $lockPath = rtrim($stateDirectory, '/').'/.'.$filename.'.lock';
        $authorityPath = rtrim($stateDirectory, '/').'/.'.$filename.'.writer-authority.json';

        return implode("\n", [
            'set -eu',
            'umask 077',
            'state_directory='.escapeshellarg($stateDirectory),
            'filename='.escapeshellarg($filename),
            'lock_path='.escapeshellarg($lockPath),
            'authority_path='.escapeshellarg($authorityPath),
            'expected_authority_base64='.escapeshellarg(base64_encode($expectedAuthority->toJson())),
            'next_authority_base64='.escapeshellarg(base64_encode($nextAuthority->toJson())),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'promoted_output='.escapeshellarg(self::WRITER_AUTHORITY_PROMOTED_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { durable_remote_assert_owned_directory "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || fail',
            '  fi',
            '}',
            'file_owner() {',
            '  if stat -c "%u:%g" "$1" >/dev/null 2>&1; then stat -c "%u:%g" "$1"; else stat -f "%u:%g" "$1"; fi',
            '}',
            'file_mode() {',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'normalize_public_authority() {',
            '  durable_remote_assert_owned_regular "$authority_path" || fail',
            '  if [ "$(id -u)" = 0 ]; then',
            '    chown 0:9999 "$authority_path" || fail',
            '    test "$(file_owner "$authority_path")" = 0:9999 || fail',
            '  fi',
            '  chmod 640 "$authority_path" || fail',
            '  test "$(file_mode "$authority_path")" = 640 || fail',
            '  durable_remote_reaffirm "$authority_path" "$state_directory" || fail',
            '}',
            'normalize_private_lock() {',
            '  durable_remote_assert_owned_regular "$lock_path" || fail',
            '  if [ "$(id -u)" = 0 ]; then',
            '    chown 0:0 "$lock_path" || fail',
            '    test "$(file_owner "$lock_path")" = 0:0 || fail',
            '  fi',
            '  chmod 600 "$lock_path" || fail',
            '  test "$(file_mode "$lock_path")" = 600 || fail',
            '  durable_remote_reaffirm "$lock_path" "$state_directory" || fail',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  if [ ! -e "$authority_candidate" ] || [ -L "$authority_candidate" ] || [ ! -f "$authority_candidate" ]; then return 1; fi',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_prefix=".managed-traefik-authority.${filename}."',
            '  durable_remote_cleanup_owned_regular_prefix "$state_directory" "$replacement_prefix" || fail',
            '  replacement_stage=$(mktemp "$state_directory/${replacement_prefix}XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$state_directory" || fail',
            '  normalize_public_authority',
            '}',
            '',
            'mkdir -p "$state_directory" || fail',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'durable_remote_assert_owned_regular "$lock_path" || fail',
            'normalize_private_lock',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$authority_path"',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-authority.XXXXXX") || fail',
            'expected_authority_file="$scratch/expected-authority"',
            'next_authority_file="$scratch/next-authority"',
            'cleanup() { rm -f "$expected_authority_file" "$next_authority_file"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'printf %s "$expected_authority_base64" | base64 -d > "$expected_authority_file" || fail',
            'printf %s "$next_authority_base64" | base64 -d > "$next_authority_file" || fail',
            'if authority_matches "$authority_path" "$next_authority_file"; then',
            '  normalize_public_authority',
            '  printf %s "$promoted_output"',
            '  exit 0',
            'fi',
            'authority_matches "$authority_path" "$expected_authority_file" || fail',
            'atomic_replace "$authority_path" "$next_authority_file"',
            'authority_matches "$authority_path" "$next_authority_file" || fail',
            'normalize_public_authority',
            'if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            'printf %s "$promoted_output"',
        ]);
    }

    private function rolledBackAuthorityReconciliationCommandFor(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): string {
        $expectedSidecar = $mutation->expectedSidecar();
        $reconciledMarker = implode("\n", [
            'coolify-managed-traefik-rollback-reconciliation-v1',
            $mutation->filename,
            $mutation->operationId,
            (string) $mutation->revision,
            $mutation->expectedSha256 ?? 'absent',
            base64_encode($rolledBackAuthority->toJson()),
            '',
        ]);

        return implode("\n", [
            'set -eu',
            'umask 077',
            'dynamic_directory='.escapeshellarg($mutation->dynamicDirectory),
            'state_directory='.escapeshellarg($mutation->stateDirectory),
            'document_path='.escapeshellarg($mutation->documentPath()),
            'sidecar_path='.escapeshellarg($mutation->sidecarPath()),
            'journal_path='.escapeshellarg($mutation->journalPath()),
            'artifact_path='.escapeshellarg($mutation->rollbackArtifactPath()),
            'lock_path='.escapeshellarg($mutation->lockPath()),
            'authority_path='.escapeshellarg($mutation->writerAuthorityPath()),
            'reconciled_marker_path='.escapeshellarg(rtrim($mutation->stateDirectory, '/').'/.'.$mutation->filename.'.'.$mutation->operationId.'.r'.$mutation->revision.'.rollback-reconciled'),
            'filename='.escapeshellarg($mutation->filename),
            'expected_document_sha='.escapeshellarg($mutation->expectedSha256 ?? 'absent'),
            'expected_sidecar_base64='.escapeshellarg($expectedSidecar === null ? 'absent' : base64_encode($expectedSidecar)),
            'predecessor_authority_base64='.escapeshellarg(base64_encode($predecessorAuthority->toJson())),
            'rolled_back_authority_base64='.escapeshellarg(base64_encode($rolledBackAuthority->toJson())),
            'reconciled_marker_base64='.escapeshellarg(base64_encode($reconciledMarker)),
            'authority_maximum_bytes='.escapeshellarg((string) ManagedTraefikDocumentWriterAuthority::MAXIMUM_SERIALIZED_BYTES),
            'artifact_magic='.escapeshellarg(self::ARTIFACT_MAGIC),
            'journal_magic='.escapeshellarg(self::JOURNAL_MAGIC),
            'reconciled_output='.escapeshellarg(self::ROLLED_BACK_OUTPUT),
            '',
            'fail() { exit 1; }',
            ...DurableRemoteArtifact::shellFunctions(),
            'assert_directory() { durable_remote_assert_owned_directory "$1" || fail; }',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    durable_remote_assert_owned_regular "$1" || fail',
            '  fi',
            '}',
            'file_owner() {',
            '  if stat -c "%u:%g" "$1" >/dev/null 2>&1; then stat -c "%u:%g" "$1"; else stat -f "%u:%g" "$1"; fi',
            '}',
            'file_mode() {',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'normalize_file_visibility() {',
            '  visibility_path=$1',
            '  visibility_owner=$2',
            '  visibility_mode=$3',
            '  durable_remote_assert_owned_regular "$visibility_path" || fail',
            '  if [ "$(id -u)" = 0 ]; then',
            '    chown "$visibility_owner" "$visibility_path" || fail',
            '    test "$(file_owner "$visibility_path")" = "$visibility_owner" || fail',
            '  fi',
            '  chmod "$visibility_mode" "$visibility_path" || fail',
            '  test "$(file_mode "$visibility_path")" = "$visibility_mode" || fail',
            '  durable_remote_reaffirm "$visibility_path" "${visibility_path%/*}" || fail',
            '}',
            'normalize_public_attestor_file() { normalize_file_visibility "$1" 0:9999 640; }',
            'normalize_private_file() { normalize_file_visibility "$1" 0:0 600; }',
            'normalize_target_visibility() {',
            '  case "$1" in',
            '    "$document_path"|"$sidecar_path"|"$authority_path") normalize_public_attestor_file "$1" ;;',
            '    *) normalize_private_file "$1" ;;',
            '  esac',
            '}',
            'normalize_visible_state() {',
            '  if [ -e "$document_path" ]; then normalize_public_attestor_file "$document_path"; fi',
            '  if [ -e "$sidecar_path" ]; then normalize_public_attestor_file "$sidecar_path"; fi',
            '  if [ -e "$authority_path" ]; then normalize_public_attestor_file "$authority_path"; fi',
            '  if [ -e "$lock_path" ]; then normalize_private_file "$lock_path"; fi',
            '  if [ -e "$journal_path" ]; then normalize_private_file "$journal_path"; fi',
            '  if [ -e "$artifact_path" ]; then normalize_private_file "$artifact_path"; fi',
            '  if [ -e "$reconciled_marker_path" ]; then normalize_private_file "$reconciled_marker_path"; fi',
            '}',
            'authority_matches() {',
            '  authority_candidate=$1',
            '  authority_expected=$2',
            '  if [ ! -e "$authority_candidate" ] || [ -L "$authority_candidate" ] || [ ! -f "$authority_candidate" ]; then return 1; fi',
            '  authority_size=$(wc -c < "$authority_candidate" | tr -d "[:space:]") || return 1',
            '  case "$authority_size" in ""|*[!0-9]*) return 1 ;; esac',
            '  test "$authority_size" -le "$authority_maximum_bytes" || return 1',
            '  cmp -s "$authority_candidate" "$authority_expected"',
            '}',
            'atomic_replace() {',
            '  replacement_target=$1',
            '  replacement_source=$2',
            '  replacement_directory=$3',
            '  replacement_prefix=".managed-traefik-reconcile.${filename}."',
            '  durable_remote_cleanup_owned_regular_prefix "$replacement_directory" "$replacement_prefix" || fail',
            '  replacement_stage=$(mktemp "$replacement_directory/${replacement_prefix}XXXXXX") || fail',
            '  cp "$replacement_source" "$replacement_stage" || fail',
            '  chmod 600 "$replacement_stage" || fail',
            '  durable_remote_replace "$replacement_stage" "$replacement_target" "$replacement_directory" || fail',
            '  normalize_target_visibility "$replacement_target"',
            '}',
            'atomic_remove() {',
            '  removal_target=$1',
            '  removal_directory=$2',
            '  assert_regular_or_absent "$removal_target"',
            '  durable_remote_remove "$removal_target" "$removal_directory" || fail',
            '}',
            'document_matches() {',
            '  document_checksum=$(sha256sum "$document_path") || return 1',
            '  test "${document_checksum%% *}" = "$1"',
            '}',
            'valid_operation_id() {',
            '  candidate_operation=$1',
            '  if [ "${#candidate_operation}" -lt 1 ] || [ "${#candidate_operation}" -gt 128 ]; then return 1; fi',
            '  case "$candidate_operation" in [a-z0-9]* ) ;; *) return 1 ;; esac',
            '  case "$candidate_operation" in *[!a-z0-9._-]* ) return 1 ;; esac',
            '}',
            'valid_revision() { case "$1" in ""|*[!0-9]*) return 1 ;; *) test "$1" -ge 1 ;; esac; }',
            'valid_sha256() { test "${#1}" -eq 64 && case "$1" in *[!a-f0-9]*) return 1 ;; *) return 0 ;; esac; }',
            'read_artifact() {',
            '  artifact_candidate=$1',
            '  artifact_size=$(wc -c < "$artifact_candidate" | tr -d "[:space:]") || return 1',
            '  valid_revision "$artifact_size" || return 1',
            '  exec 8< "$artifact_candidate" || return 1',
            '  IFS= read -r artifact_line_1 <&8 || return 1',
            '  IFS= read -r artifact_line_2 <&8 || return 1',
            '  IFS= read -r artifact_line_3 <&8 || return 1',
            '  IFS= read -r artifact_line_4 <&8 || return 1',
            '  IFS= read -r artifact_line_5 <&8 || return 1',
            '  IFS= read -r artifact_line_6 <&8 || return 1',
            '  IFS= read -r artifact_line_7 <&8 || return 1',
            '  IFS= read -r artifact_line_8 <&8 || return 1',
            '  IFS= read -r artifact_extra <&8 && { : "$artifact_extra"; return 1; }',
            '  exec 8<&- || return 1',
            '  test "$artifact_line_1" = "$artifact_magic" || return 1',
            '  test "$artifact_line_2" = "$filename" || return 1',
            '  test "$artifact_line_5" = "$expected_document_sha" || return 1',
            '  test "$artifact_line_7" = "$expected_sidecar_base64" || return 1',
            '  valid_operation_id "$artifact_line_3" || return 1',
            '  valid_revision "$artifact_line_4" || return 1',
            '  valid_sha256 "$artifact_line_6" || return 1',
            '  printf %s "$artifact_line_8" | base64 -d > "$candidate_predecessor_file" || return 1',
            '  predecessor_checksum=$(sha256sum "$candidate_predecessor_file") || return 1',
            '  test "${predecessor_checksum%% *}" = "$expected_document_sha" || return 1',
            '  printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$artifact_line_3" "$artifact_line_4" "$artifact_line_6" > "$candidate_sidecar_file" || return 1',
            '}',
            'validate_pending_journal() {',
            '  journal_size=$(wc -c < "$journal_path" | tr -d "[:space:]") || fail',
            '  valid_revision "$journal_size" || fail',
            '  exec 7< "$journal_path" || fail',
            '  IFS= read -r journal_line_1 <&7 || fail',
            '  IFS= read -r journal_line_2 <&7 || fail',
            '  IFS= read -r journal_line_3 <&7 || fail',
            '  IFS= read -r journal_line_4 <&7 || fail',
            '  IFS= read -r journal_line_5 <&7 || fail',
            '  IFS= read -r journal_line_6 <&7 || fail',
            '  IFS= read -r journal_line_7 <&7 || fail',
            '  IFS= read -r journal_line_8 <&7 || fail',
            '  IFS= read -r journal_line_9 <&7 || fail',
            '  IFS= read -r journal_line_10 <&7 || fail',
            '  IFS= read -r journal_extra <&7 && { : "$journal_extra"; fail; }',
            '  exec 7<&- || fail',
            '  test "$journal_line_1" = "$journal_magic" || fail',
            '  test "$journal_line_3" = "$filename" || fail',
            '  valid_operation_id "$journal_line_4" || fail',
            '  valid_revision "$journal_line_5" || fail',
            '  journal_operation=$journal_line_4',
            '  journal_revision=$journal_line_5',
            '  case "$journal_line_2" in',
            '    write)',
            '      test "$journal_line_6" = "$expected_document_sha" || fail',
            '      test "$journal_line_8" = "$expected_sidecar_base64" || fail',
            '      valid_sha256 "$journal_line_7" || fail',
            '      journal_successor_sha=$journal_line_7',
            '      printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$journal_operation" "$journal_revision" "$journal_successor_sha" > "$journal_sidecar_file" || fail',
            '      test "$(base64 < "$journal_sidecar_file" | tr -d "\\n")" = "$journal_line_9" || fail',
            '      printf %s "$journal_line_10" | base64 -d > "$successor_document_file" || fail',
            '      journal_payload_checksum=$(sha256sum "$successor_document_file") || fail',
            '      test "${journal_payload_checksum%% *}" = "$journal_successor_sha" || fail',
            '      ;;',
            '    rollback)',
            '      valid_sha256 "$journal_line_6" || fail',
            '      test "$journal_line_7" = "$expected_document_sha" || fail',
            '      test "$journal_line_9" = "$expected_sidecar_base64" || fail',
            '      journal_successor_sha=$journal_line_6',
            '      printf \'{"version":1,"filename":"%s","operation_id":"%s","revision":%s,"sha256":"%s"}\\n\' "$filename" "$journal_operation" "$journal_revision" "$journal_successor_sha" > "$journal_sidecar_file" || fail',
            '      test "$(base64 < "$journal_sidecar_file" | tr -d "\\n")" = "$journal_line_8" || fail',
            '      printf %s "$journal_line_10" | base64 -d > "$predecessor_document_file" || fail',
            '      journal_payload_checksum=$(sha256sum "$predecessor_document_file") || fail',
            '      test "${journal_payload_checksum%% *}" = "$expected_document_sha" || fail',
            '      ;;',
            '    *) fail ;;',
            '  esac',
            '}',
            '',
            'assert_directory "$dynamic_directory"',
            'assert_directory "$state_directory"',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$reconciled_marker_path"',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'durable_remote_assert_owned_regular "$lock_path" || fail',
            'normalize_private_file "$lock_path"',
            'flock -x 9 || fail',
            'assert_regular_or_absent "$document_path"',
            'assert_regular_or_absent "$sidecar_path"',
            'assert_regular_or_absent "$journal_path"',
            'assert_regular_or_absent "$artifact_path"',
            'assert_regular_or_absent "$authority_path"',
            'assert_regular_or_absent "$reconciled_marker_path"',
            'test "$expected_document_sha" != absent || fail',
            'if [ ! -e "$document_path" ] || [ -L "$document_path" ] || [ ! -f "$document_path" ]; then fail; fi',
            'scratch=$(mktemp -d "$state_directory/.managed-traefik-authority.XXXXXX") || fail',
            'expected_sidecar_file="$scratch/expected-sidecar"',
            'successor_sidecar_file="$scratch/successor-sidecar"',
            'predecessor_authority_file="$scratch/predecessor-authority"',
            'rolled_back_authority_file="$scratch/rolled-back-authority"',
            'predecessor_document_file="$scratch/predecessor-document"',
            'successor_document_file="$scratch/successor-document"',
            'candidate_predecessor_file="$scratch/candidate-predecessor"',
            'candidate_sidecar_file="$scratch/candidate-sidecar"',
            'journal_sidecar_file="$scratch/journal-sidecar"',
            'reconciled_marker_file="$scratch/reconciled-marker"',
            'cleanup() { rm -f "$expected_sidecar_file" "$successor_sidecar_file" "$predecessor_authority_file" "$rolled_back_authority_file" "$predecessor_document_file" "$successor_document_file" "$candidate_predecessor_file" "$candidate_sidecar_file" "$journal_sidecar_file" "$reconciled_marker_file"; rmdir "$scratch" 2>/dev/null || true; }',
            'trap cleanup 0 HUP INT TERM',
            'test "$expected_sidecar_base64" != absent || fail',
            'printf %s "$expected_sidecar_base64" | base64 -d > "$expected_sidecar_file" || fail',
            'printf %s "$predecessor_authority_base64" | base64 -d > "$predecessor_authority_file" || fail',
            'printf %s "$rolled_back_authority_base64" | base64 -d > "$rolled_back_authority_file" || fail',
            'printf %s "$reconciled_marker_base64" | base64 -d > "$reconciled_marker_file" || fail',
            'if ! authority_matches "$authority_path" "$rolled_back_authority_file"; then',
            '  if [ -e "$authority_path" ] || [ -L "$authority_path" ]; then',
            '  authority_matches "$authority_path" "$predecessor_authority_file" || fail',
            '  fi',
            '  atomic_replace "$authority_path" "$rolled_back_authority_file" "$state_directory"',
            'fi',
            'authority_matches "$authority_path" "$rolled_back_authority_file" || fail',
            'normalize_public_attestor_file "$authority_path"',
            'if [ "${COOLIFY_MANAGED_TRAEFIK_DOCUMENT_CRASH_AFTER_AUTHORITY:-}" = 1 ]; then exit 75; fi',
            'if [ -e "$reconciled_marker_path" ] || [ -L "$reconciled_marker_path" ]; then',
            '  cmp -s "$reconciled_marker_path" "$reconciled_marker_file" || fail',
            '  if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then fail; fi',
            '  document_matches "$expected_document_sha" || fail',
            '  cmp -s "$sidecar_path" "$expected_sidecar_file" || fail',
            '  durable_remote_remove "$journal_path" "$state_directory" || fail',
            '  normalize_visible_state',
            '  printf %s "$reconciled_output"',
            '  exit 0',
            'fi',
            'journal_present=false',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then validate_pending_journal; journal_present=true; fi',
            'if document_matches "$expected_document_sha" && cmp -s "$sidecar_path" "$expected_sidecar_file" && [ "$journal_present" = false ]; then',
            '  atomic_replace "$reconciled_marker_path" "$reconciled_marker_file" "$state_directory"',
            '  normalize_visible_state',
            '  printf %s "$reconciled_output"',
            '  exit 0',
            'fi',
            'live_document_checksum=$(sha256sum "$document_path") || fail',
            'live_document_sha=${live_document_checksum%% *}',
            'selected_artifact=false',
            'for artifact_candidate in "$state_directory"/."$filename".*.r*.rollback; do',
            '  test -e "$artifact_candidate" || continue',
            '  if [ -L "$artifact_candidate" ] || [ ! -f "$artifact_candidate" ]; then continue; fi',
            '  read_artifact "$artifact_candidate" || continue',
            '  if [ "$journal_present" = true ]; then',
            '    if [ "$artifact_line_3" != "$journal_operation" ] || [ "$artifact_line_4" != "$journal_revision" ] || [ "$artifact_line_6" != "$journal_successor_sha" ]; then continue; fi',
            '  fi',
            '  if { [ "$journal_present" = true ] && { test "$live_document_sha" = "$expected_document_sha" || test "$live_document_sha" = "$artifact_line_6"; } && { cmp -s "$sidecar_path" "$expected_sidecar_file" || cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; } || { test "$live_document_sha" = "$artifact_line_6" && { cmp -s "$sidecar_path" "$expected_sidecar_file" || cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; } || { test "$live_document_sha" = "$expected_document_sha" && cmp -s "$sidecar_path" "$candidate_sidecar_file"; }; then',
            '    cp "$candidate_predecessor_file" "$predecessor_document_file" || fail',
            '    cp "$candidate_sidecar_file" "$successor_sidecar_file" || fail',
            '    selected_artifact=true',
            '    break',
            '  fi',
            'done',
            'test "$selected_artifact" = true || fail',
            'if ! document_matches "$expected_document_sha"; then atomic_replace "$document_path" "$predecessor_document_file" "$dynamic_directory"; fi',
            'if ! cmp -s "$sidecar_path" "$expected_sidecar_file"; then atomic_replace "$sidecar_path" "$expected_sidecar_file" "$state_directory"; fi',
            'document_matches "$expected_document_sha" || fail',
            'cmp -s "$sidecar_path" "$expected_sidecar_file" || fail',
            'if [ -e "$journal_path" ] || [ -L "$journal_path" ]; then atomic_remove "$journal_path" "$state_directory"; fi',
            'atomic_replace "$reconciled_marker_path" "$reconciled_marker_file" "$state_directory"',
            'durable_remote_remove "$journal_path" "$state_directory" || fail',
            'normalize_visible_state',
            'printf %s "$reconciled_output"',
        ]);
    }

    private function assertDocumentWriteAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $activeAuthority,
        bool $allowBootstrap,
    ): void {
        if ($allowBootstrap) {
            if ($activeAuthority->epoch !== 1 || ! $activeAuthority->matchesPredecessor($mutation)) {
                throw new InvalidArgumentException('Managed Traefik document writer authority bootstrap is limited to the exact initial epoch-one predecessor authority.');
            }

            return;
        }

        if (! $activeAuthority->matchesPredecessor($mutation)) {
            throw new InvalidArgumentException('The managed Traefik document write must require the exact active predecessor authority.');
        }
    }

    private function assertEnrollmentRollbackFinalizationAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): void {
        if ($mutation->expectedSidecar() !== null
            || $rolledBackAuthority->epoch !== 2
            || ! hash_equals($rolledBackAuthority->operationId, $mutation->operationId)
            || $rolledBackAuthority->dynamicRevision !== $mutation->revision
            || ! hash_equals(
                $rolledBackAuthority->dynamicSha256,
                $mutation->expectedSha256 ?? hash('sha256', ''),
            )) {
            throw new InvalidArgumentException('Enrollment rollback finalization requires the exact rolled-back authority and an unmanaged predecessor state.');
        }
    }

    private function assertAuthorityPromotion(
        ManagedTraefikDocumentWriterAuthority $expectedAuthority,
        ManagedTraefikDocumentWriterAuthority $nextAuthority,
    ): void {
        if ($nextAuthority->epoch !== $expectedAuthority->epoch + 1) {
            throw new InvalidArgumentException('A managed Traefik document writer authority promotion must advance exactly one epoch.');
        }
    }

    private function assertWriterAuthorityContext(string $stateDirectory, string $filename): void
    {
        if (! str_starts_with($stateDirectory, '/') || str_contains($stateDirectory, "\0")) {
            throw new InvalidArgumentException('The managed Traefik document writer authority state directory must be an absolute NUL-free path.');
        }

        if (basename($filename) !== $filename
            || preg_match('/\A[a-z0-9][a-z0-9.-]{0,127}\.ya?ml\z/D', $filename) !== 1) {
            throw new InvalidArgumentException('The managed Traefik document writer authority filename is invalid.');
        }
    }

    private function assertRollbackAuthority(
        ManagedTraefikDocumentMutation $mutation,
        ManagedTraefikDocumentWriterAuthority $predecessorAuthority,
        ManagedTraefikDocumentWriterAuthority $rolledBackAuthority,
    ): void {
        if (! $predecessorAuthority->matchesPredecessor($mutation)) {
            throw new InvalidArgumentException('The managed Traefik document rollback must require the exact predecessor authority and cannot downgrade a successor authority.');
        }
        if ($rolledBackAuthority->epoch !== $predecessorAuthority->epoch + 1
            || ! hash_equals($rolledBackAuthority->operationId, $mutation->operationId)
            || ! $rolledBackAuthority->matchesPredecessorDocument($mutation)
            || ! $rolledBackAuthority->hasSameWriterIdentityAs($predecessorAuthority)) {
            throw new InvalidArgumentException('The managed Traefik document rollback authority must fence the exact generation attempt while preserving its predecessor writer.');
        }
    }
}
