<?php

namespace App\Actions\Proxy\ControlPlane;

use InvalidArgumentException;
use Lorisleiva\Actions\Concerns\AsAction;

final class NormalizeControlPlaneEnrollmentFilesystem
{
    use AsAction;

    public const NORMALIZED_OUTPUT = 'coolify-control-plane-enrollment-filesystem:normalized';

    public function handle(string $proxyPath, string $sourceDirectory = '/data/coolify/source'): string
    {
        return $this->commandFor($proxyPath, $sourceDirectory);
    }

    public function commandFor(string $proxyPath, string $sourceDirectory = '/data/coolify/source'): string
    {
        $this->assertAbsolutePath($proxyPath, 'proxy path');
        $this->assertAbsolutePath($sourceDirectory, 'source directory');

        $proxyPath = rtrim($proxyPath, '/');
        $sourceDirectory = rtrim($sourceDirectory, '/');
        $dynamicDirectory = $proxyPath.'/dynamic';
        $stateDirectory = $proxyPath.'/.control-plane-managed-traefik';
        $managedFilename = ControlPlaneDynamicConfiguration::MANAGED_FILENAME;

        return implode("\n", [
            'set -eu',
            'umask 077',
            'proxy_directory='.escapeshellarg($proxyPath),
            'dynamic_directory='.escapeshellarg($dynamicDirectory),
            'state_directory='.escapeshellarg($stateDirectory),
            'source_directory='.escapeshellarg($sourceDirectory),
            'proxy_compose_path='.escapeshellarg($proxyPath.'/docker-compose.yml'),
            'source_environment_path='.escapeshellarg($sourceDirectory.'/.env'),
            'source_override_path='.escapeshellarg($sourceDirectory.'/docker-compose.control-plane-listener.yml'),
            'managed_document_path='.escapeshellarg($dynamicDirectory.'/'.$managedFilename),
            'sidecar_path='.escapeshellarg($stateDirectory.'/.'.$managedFilename.'.state.json'),
            'authority_path='.escapeshellarg($stateDirectory.'/.'.$managedFilename.'.writer-authority.json'),
            'lock_path='.escapeshellarg($stateDirectory.'/.'.$managedFilename.'.lock'),
            'journal_path='.escapeshellarg($stateDirectory.'/.'.$managedFilename.'.pending-mutation'),
            'normalized_output='.escapeshellarg(self::NORMALIZED_OUTPUT),
            '',
            'fail() { exit 1; }',
            'file_owner() {',
            '  if stat -c "%u:%g" "$1" >/dev/null 2>&1; then stat -c "%u:%g" "$1"; else stat -f "%u:%g" "$1"; fi',
            '}',
            'file_mode() {',
            '  if stat -c "%a" "$1" >/dev/null 2>&1; then stat -c "%a" "$1"; else stat -f "%Lp" "$1"; fi',
            '}',
            'assert_regular_or_absent() {',
            '  if [ -e "$1" ] || [ -L "$1" ]; then',
            '    [ -f "$1" ] && [ ! -L "$1" ] || fail',
            '    [ "$(file_link_count "$1")" = 1 ] || fail',
            '  fi',
            '}',
            'file_link_count() {',
            '  if stat -c "%h" "$1" >/dev/null 2>&1; then stat -c "%h" "$1"; else stat -f "%l" "$1"; fi',
            '}',
            'assert_safe_tree() {',
            '  [ -d "$1" ] && [ ! -L "$1" ] || fail',
            '  unsafe_link=$(find "$1" -xdev -type l -print -quit) || fail',
            '  [ -z "$unsafe_link" ] || fail',
            '  unsafe_hard_link=$(find "$1" -xdev -type f -links +1 -print -quit) || fail',
            '  [ -z "$unsafe_hard_link" ] || fail',
            '}',
            'assert_exact_metadata() {',
            '  [ "$(file_owner "$1")" = "$2" ] || fail',
            '  [ "$(file_mode "$1")" = "$3" ] || fail',
            '}',
            'set_directory_metadata() {',
            '  path=$1',
            '  owner=$2',
            '  mode=$3',
            '  chown "$owner" "$path" || fail',
            '  chmod "$mode" "$path" || fail',
            '  assert_exact_metadata "$path" "$owner" "$mode"',
            '}',
            'set_file_metadata() {',
            '  path=$1',
            '  owner=$2',
            '  mode=$3',
            '  assert_regular_or_absent "$path"',
            '  [ -e "$path" ] || return 0',
            '  chown "$owner" "$path" || fail',
            '  chmod "$mode" "$path" || fail',
            '  assert_exact_metadata "$path" "$owner" "$mode"',
            '}',
            'set_private_state_file_metadata() {',
            '  set_file_metadata "$1" 0:0 600',
            '}',
            'set_public_attestor_file_metadata() {',
            '  set_file_metadata "$1" 0:9999 640',
            '}',
            'classify_state_file() {',
            '  case "${1##*/}" in',
            '    .coolify.yaml.state.json|.coolify.yaml.writer-authority.json) printf "%s\\n" public ;;',
            '    .coolify.yaml.lock|.coolify.yaml.pending-mutation|.coolify.yaml.*.r*.rollback|.coolify.yaml.*.r*.rollback-reconciled|.managed-traefik-document.*|.managed-traefik-journal.*|.managed-traefik-artifact.*|.managed-traefik-authority.*|.managed-traefik-reconcile.*) printf "%s\\n" private ;;',
            '    *) return 1 ;;',
            '  esac',
            '}',
            'remove_owned_crash_directory() {',
            '  crash_directory=$1',
            '  [ -d "$crash_directory" ] && [ ! -L "$crash_directory" ] || fail',
            '  [ "${2:-}" = allowed ] || fail',
            '  [ "${crash_directory##*/}" != . ] && [ "${crash_directory##*/}" != .. ] || fail',
            '  crash_directory_owner=$(file_owner "$crash_directory") || fail',
            '  [ "${crash_directory_owner%%:*}" = 0 ] || fail',
            '  assert_safe_tree "$crash_directory"',
            '  for crash_child in "$crash_directory"/* "$crash_directory"/.*; do',
            '    [ -e "$crash_child" ] || [ -L "$crash_child" ] || continue',
            '    case "${crash_child##*/}" in .|..) continue ;; esac',
            '    [ -f "$crash_child" ] && [ ! -L "$crash_child" ] || fail',
            '    [ "$(file_link_count "$crash_child")" = 1 ] || fail',
            '    file_owner_child=$(file_owner "$crash_child") || fail',
            '    [ "${file_owner_child%%:*}" = 0 ] || fail',
            '  done',
            '  rm -f -- "$crash_directory"/* "$crash_directory"/.* 2>/dev/null || true',
            '  rmdir "$crash_directory" || fail',
            '}',
            'cleanup_owned_crash_debris() {',
            '  for crash_path in "$state_directory"/.control-plane-enrollment-writer-authority-scratch.* "$state_directory"/.managed-traefik-document.* "$state_directory"/.managed-traefik-authority.* "$state_directory"/.managed-traefik-reconcile.*; do',
            '    [ -e "$crash_path" ] || [ -L "$crash_path" ] || continue',
            '    [ -d "$crash_path" ] && [ ! -L "$crash_path" ] || continue',
            '    remove_owned_crash_directory "$crash_path" allowed',
            '  done',
            '  for crash_path in "$state_directory"/.control-plane-enrollment-writer-authority.*; do',
            '    [ -e "$crash_path" ] || [ -L "$crash_path" ] || continue',
            '    case "${crash_path##*/}" in .control-plane-enrollment-writer-authority-scratch.*) continue ;; esac',
            '    [ -f "$crash_path" ] && [ ! -L "$crash_path" ] || fail',
            '    [ "$(file_link_count "$crash_path")" = 1 ] || fail',
            '    file_owner_result=$(file_owner "$crash_path") || fail',
            '    [ "${file_owner_result%%:*}" = 0 ] || fail',
            '    rm -f -- "$crash_path" || fail',
            '  done',
            '  sync "$state_directory" || fail',
            '}',
            'test "$(id -u)" = 0 || fail',
            '# Validate every existing inode before changing ownership or mode.',
            'assert_safe_tree "$proxy_directory"',
            'assert_safe_tree "$dynamic_directory"',
            'assert_safe_tree "$source_directory"',
            'assert_regular_or_absent "$proxy_compose_path"',
            'test -e "$proxy_compose_path" || fail',
            'assert_regular_or_absent "$source_environment_path"',
            'test -e "$source_environment_path" || fail',
            'assert_regular_or_absent "$source_override_path"',
            'assert_regular_or_absent "$managed_document_path"',
            'if [ -e "$state_directory" ] || [ -L "$state_directory" ]; then',
            '  assert_safe_tree "$state_directory"',
            'else',
            '  mkdir "$state_directory" || fail',
            '  assert_safe_tree "$state_directory"',
            'fi',
            '# Revoke the legacy UID 9999 write boundary before any child metadata mutation.',
            'chown -h 0:9999 "$proxy_directory" || fail',
            'assert_safe_tree "$proxy_directory"',
            'chmod 0710 "$proxy_directory" || fail',
            'chown -h 0:9999 "$dynamic_directory" "$state_directory" || fail',
            'assert_safe_tree "$dynamic_directory"',
            'assert_safe_tree "$state_directory"',
            'chmod 0710 "$dynamic_directory" "$state_directory" || fail',
            'chown -h 0:0 "$source_directory" || fail',
            'assert_safe_tree "$source_directory"',
            'chmod 0710 "$source_directory" || fail',
            'assert_regular_or_absent "$lock_path"',
            'command -v flock >/dev/null 2>&1 || fail',
            'exec 9> "$lock_path" || fail',
            'set_private_state_file_metadata "$lock_path"',
            'flock -x 9 || fail',
            'cleanup_owned_crash_debris',
            'for state_path in "$state_directory"/* "$state_directory"/.*; do',
            '  [ -e "$state_path" ] || [ -L "$state_path" ] || continue',
            '  case "${state_path##*/}" in .|..) continue ;; esac',
            '  [ -f "$state_path" ] && [ ! -L "$state_path" ] || fail',
            '  [ "$(file_link_count "$state_path")" = 1 ] || fail',
            '  classify_state_file "$state_path" >/dev/null || fail',
            'done',
            'for dynamic_path in "$dynamic_directory"/* "$dynamic_directory"/.*; do',
            '  [ -e "$dynamic_path" ] || [ -L "$dynamic_path" ] || continue',
            '  case "${dynamic_path##*/}" in .|..) continue ;; esac',
            '  [ -f "$dynamic_path" ] && [ ! -L "$dynamic_path" ] || fail',
            '  [ "$(file_link_count "$dynamic_path")" = 1 ] || fail',
            'done',
            '# The root command owns durable writes. The attestor gets group-read only for its three proofs.',
            'set_directory_metadata "$proxy_directory" 0:9999 710',
            'set_directory_metadata "$dynamic_directory" 0:9999 710',
            'set_directory_metadata "$state_directory" 0:9999 710',
            'set_directory_metadata "$source_directory" 0:0 710',
            'set_file_metadata "$proxy_compose_path" 0:0 600',
            'set_file_metadata "$source_environment_path" 9999:0 600',
            'set_file_metadata "$source_override_path" 0:0 600',
            'for dynamic_path in "$dynamic_directory"/* "$dynamic_directory"/.*; do',
            '  [ -e "$dynamic_path" ] || continue',
            '  case "${dynamic_path##*/}" in .|..) continue ;; esac',
            '  if [ "$dynamic_path" = "$managed_document_path" ]; then',
            '    set_public_attestor_file_metadata "$dynamic_path"',
            '  else',
            '    set_private_state_file_metadata "$dynamic_path"',
            '  fi',
            'done',
            'for state_path in "$state_directory"/* "$state_directory"/.*; do',
            '  [ -e "$state_path" ] || continue',
            '  case "${state_path##*/}" in .|..) continue ;; esac',
            '  case "$(classify_state_file "$state_path")" in',
            '    public) set_public_attestor_file_metadata "$state_path" ;;',
            '    private) set_private_state_file_metadata "$state_path" ;;',
            '    *) fail ;;',
            '  esac',
            'done',
            'set_public_attestor_file_metadata "$managed_document_path"',
            'set_public_attestor_file_metadata "$sidecar_path"',
            'set_public_attestor_file_metadata "$authority_path"',
            'set_private_state_file_metadata "$lock_path"',
            'set_private_state_file_metadata "$journal_path"',
            'printf %s "$normalized_output"',
        ]);
    }

    private function assertAbsolutePath(string $path, string $label): void
    {
        if (! str_starts_with($path, '/') || str_contains($path, "\0") || rtrim($path, '/') === '') {
            throw new InvalidArgumentException("The control-plane {$label} must be an absolute NUL-free path.");
        }
    }
}
